export const EN_TEXTS = {
  // Regional terminology
  orderAttendant: 'Waiter',
  changeOrderAttendant: 'Change waiter',
  selectOrderAttendant: 'Select a waiter',
  orderAttendantRequired: 'You must select a waiter.',
  onlyAdminCanChangeOrderAttendant:
    'Only an administrator can change the waiter.',
  couldNotChangeOrderAttendant: 'The waiter could not be changed.',
  unexpectedOrderAttendantChangeError:
    'An error occurred while changing the waiter.',

  // Common actions and states
  accept: 'Accept',
  cancel: 'Cancel',
  close: 'Close',
  closeDialog: 'Close dialog',
  delete: 'Delete',
  error: 'Error',
  validation: 'Validation',
  exit: 'Exit',
  search: 'Search',
  retry: 'Retry',
  save: 'Save',
  saving: 'Saving…',
  openStatus: 'OPEN',
  closedStatus: 'CLOSED',
  language: 'Language',
  useTenantLanguage: 'Use business language',
  cultureChangeError: 'The language preference could not be changed.',

  // Application and login
  restaurantManagement: 'Agile management for restaurants and hospitality',
  installApplication: 'Install application',
  invalidCredentials: 'Incorrect username or password. Please try again.',
  branch: 'Branch',
  user: 'User',
  usernamePlaceholder: 'Enter your username',
  password: 'Password',
  passwordPlaceholder: 'Enter your password',
  showPassword: 'Show password',
  hidePassword: 'Hide password',
  numericKeypad: 'Numeric keypad',
  signIn: 'Sign in',
  signingIn: 'Signing in…',
  forgotPassword: 'Forgot your password?',
  checkYourEmail: 'Check your email',
  resetEmailSentPrefix: 'If user',
  resetEmailSentSuffix:
    'has a registered email, you will receive a password reset link in the next few minutes.',
  backToLogin: 'Back to sign in',
  back: 'Back',
  recoverPassword: 'Recover password',
  recoverPasswordHint: 'We will send a link to your registered email.',
  usernameNamePlaceholder: 'Enter your username',
  sendInstructions: 'Send instructions',
  sending: 'Sending…',
  applicationVersion: 'Application version',
  serverOffline: 'No connection to the server',
  operationsUnavailable: 'operations are unavailable',
  enterPassword: 'Enter password',
  noBusinessRole:
    'The user does not have a business role assigned in Keycloak.',
  couldNotLoadStations: 'The station list could not be loaded.',
  stationNotConfigured: 'Station not configured',
  stationIdentifierMissing:
    'This device does not have a station identifier. Contact the administrator.',
  selectBranchAndUser: 'Select a branch and enter your username.',
  iosInstallHint:
    'To install the application on iOS, open the share menu and select "Add to Home Screen".',
  couldNotLoadTenants: 'The tenant list could not be loaded.',
  noTenantsAvailable:
    'There are no tenants available. Contact the administrator.',
  couldNotLoadTenantsRetry:
    'Tenants could not be loaded. Please try again.',

  // Header and navigation
  openMenu: 'Open menu',
  restaurant: 'Restaurant',
  shift: 'Shift',
  noShift: 'No shift',
  shiftSales: 'Shift sales',
  orders: 'Orders',
  averageTicket: 'Average ticket',
  home: 'Home',
  logout: 'Log out',
  dashboard: 'Dashboard',
  administration: 'Administration',
  register: 'Register',
  noOpenShiftForStation: 'There is no open shift for this station',
  componentWillClose: 'This screen will close.',
  change: 'Change',

  // Sales screen
  goToAdministration: 'Go to Administration',
  administrationShortcut: 'Administration (Ctrl+Alt+A)',
  date: 'Date',
  tableChannel: 'TABLE CHANNEL',
  takeawayChannel: 'TAKEAWAY CHANNEL',
  deliveryChannel: 'DELIVERY CHANNEL',
  admission: 'ADMISSION',
  refresh: 'REFRESH',
  orderNumber: 'Order No.',
  delivery: 'Delivery',
  phone: 'Phone',
  customer: 'Customer',
  order: 'Order',
  product: 'Product',
  observation: 'Note',
  hostess: 'Hostess',
  couponNumber: 'Coupon No.',
  withComplement: 'With complement',
  price: 'Price',
  quantity: 'Qty',
  increaseQuantity: 'Increase quantity',
  decreaseQuantity: 'Decrease quantity',
  moreOptions: 'More options',
  moveToAnotherTable: 'Move to another table',
  courtesyDrink: 'Complimentary drink',
  amount: 'Amount',
  discount: 'Discount',
  removeDiscount: 'Remove discount',
  total: 'Total',
  bagTax: 'Bag',
  preBill: 'Pre-bill',
  issuedDocuments: 'Issued documents',
  expensesReports: 'Expenses / Reports',
  combo: 'Combo',
  viewComplements: 'View complements',
  viewComplement: 'View complement',
  express: 'Express',
  sendOrder: 'Send order',
  lock: 'Lock',
  reset: 'Reset',
  prioritizeDispatch: 'Prioritize dispatch',
  cancelOrder: 'Cancel order',
  reprint: 'Reprint',
  mergeTablePrefix: 'will be merged into the selected table',
  occupiedTablesOnly: 'only occupied tables are shown',
  selectFreeTableForOrder: 'Select a free table to move the order',
  selectDestinationTable: 'Select the destination table for',
  verifyBackend: 'Check that the backend is running and try again.',
  newOrder: 'New order',
  processOrder: 'Process order',
  moveToTable: 'Move to table',
  changeSpace: 'Change space',
  mergeAccount: 'Merge account',
  splitAccount: 'Split account',
  activateSpace: 'Activate space',
  searchProducts: 'Search products',
  selectSpace: 'Select a space.',
  mergeSpace: 'Merge space',
  changeSpaceTitle: 'Change space',
  customerNamePlaceholder: 'Enter the customer name',
  courtesyCodeEntered: 'Complimentary code entered',
  enteredCode: 'The entered code is: {{code}}',
  deleteCode: 'Delete code',
  keepCode: 'Keep code',
  codeDeleted: 'Code deleted',
  enterCourtesyCode: 'Enter complimentary code',
  enterHostessCodes: 'Enter hostess codes',
  codeLabel: 'Code {{number}}',
  addMore: 'Add more',
  enterHostessCode: 'Enter hostess code {{number}}',
  orderNotFound: 'The order does not exist.',
  productTransfer: 'Product transfer',
  selectTable: 'You must select a table.',
  transferToTable: 'Transfer to table',
  selectOrder: 'You must select an order.',
  couldNotMoveOrder: 'The order could not be transferred.',
  errorMovingOrder: 'An error occurred while transferring the order.',
  couldNotTransferProduct: 'The product could not be transferred.',
  errorMovingProduct: 'An error occurred while transferring the product.',
  enterGuestCount: 'Enter number of guests',
  positiveNumberRequired: 'Enter a valid number greater than zero.',
  orderNotFoundInSpace: 'The order does not exist in this space.',
  unexpectedError: 'Something went wrong',
  addQuantityFirst: 'Add a quantity first.',
  confirmDeleteProduct: 'Are you sure you want to delete {{product}}?',
  enterAdministratorCode: 'Enter administrator code',
  invalidCode: 'Invalid code',
  incorrectCode: 'The entered code is incorrect.',
  enterPrice: 'Enter price',
  confirmVoidSpaceOrder:
    'Are you sure you want to void the order for {{space}}?',
  processOrderTitle: 'Process order',
  confirmRemoveDiscount: 'Are you sure you want to remove the discount?',
  yes: 'Yes',
  no: 'No',
  orderNotFoundInAccount: 'The order does not exist in the account.',
  printPreBill: 'Print pre-bill',
  noProductsEntered: 'No products have been entered.',
  allProductsMustBeSaved: 'Not all products in the list were saved.',
  orderMustBeSaved: 'The entire order must be saved.',
  internalErrorRefresh: 'Internal error. Please refresh.',

  // Shift dialogs
  closeShift: 'Close shift',
  shiftNumber: 'Shift No.',
  startDate: 'Start date',
  currentDate: 'Current date',
  exchangeRate: 'Exchange rate',
  status: 'Status',
  shiftClosed: 'SHIFT CLOSED',
  selectOpenShiftRegister:
    'Select a register with an open shift to close it.',
  partialClose: 'Partial close',
  partialCloseHint: 'Skips validation of unpaid orders.',
  pendingOrdersTitle: 'Orders pending payment ({{count}})',
  pendingOrdersExplanation:
    'These orders prevent the shift from closing. You can void them here or leave to collect them from Sales. Then try closing the shift again.',
  account: 'Account',
  spaceOrChannel: 'Space / channel',
  void: 'Void',
  revalidateClose: 'Revalidate close',
  openShift: 'Open shift',
  shiftOpened: 'Shift {{number}} open',
  registerAlreadyOperational:
    'The selected register is already operational. It does not need to be opened again.',
  selectRegister: 'Select a register.',
  enterExchangeRate: 'Enter the exchange rate.',
  enterPositiveValue: 'Enter a value greater than zero.',
  workDate: 'Work date',
  openAction: 'Open',
  noOpenShiftForRegister: 'There is no open shift for this register.',
  couldNotCloseShift: 'The shift could not be closed.',
  shiftCloseTitle: 'Shift closing',
  shiftClosedSuccessfully: 'The shift was closed successfully.',
  voidOrderTitle: 'Void order No. {{number}}',
  voidOrderWarning:
    'This operation will void the entire order and cannot be undone.',
  voidReason: 'Void reason',
  enterVoidReason: 'Enter the reason...',
  voidOrder: 'Void order',
  voidReasonRequired: 'You must enter the void reason.',
  couldNotVoidOrder: 'The order could not be voided.',
  orderVoided: 'Order voided',
  orderVoidedSuccessfully: 'The order was voided successfully.',
  unpaidSalesTitle: 'Sales without a recorded payment',
  unpaidSalesQuestion:
    'There are sales without a recorded payment. Are they credit sales?',
  document: 'Document',
  confirmCreditSales: 'Yes, they are credit sales',
  shiftOpenedTitle: 'Shift opened',
  registerAvailableForOperations:
    'The register is now available to record operations.',

  // Delivery
  newDelivery: 'New delivery',
  chooseDeliveryOrigin:
    'Choose how the order was received before identifying the customer.',
  businessPartnersCount: '{{count}} business partners',
  deliveryMode: 'Delivery method',
  phoneDelivery: 'Delivery by phone',
  phoneDeliveryHint:
    'Find or register the customer phone number and address.',
  businessPartnerOrder: 'Order from a business partner',
  businessPartnerExamples:
    'Glovo, Uber Eats or another platform with its own prices.',
  noBusinessPartners: 'No business partners are configured.',
  selectDeliveryMode: 'Select a method to continue',
  selectDeliveryModeHint:
    'This keeps the order origin and pricing rules correct.',
  externalOrderData: 'External order details',
  noPhoneRecordForExternalOrder:
    'A phone record is not created for this order',
  businessPartner: 'Business partner',
  selectOriginBusinessPartner:
    'Select the business partner that originated the order.',
  customerName: 'Customer name',
  customerNameRequired: 'The customer name is required.',
  unnamedCustomer: 'No name',
  businessPartnerPricesHint:
    'Configured partner prices will be applied. Products without a special price will keep their normal price.',
  deliverySearchLabel: 'Phone, customer, document or address',
  clearSearch: 'Clear search',
  newDestination: 'New destination',
  destinationsFound: 'Destinations found',
  destinations: 'Destinations',
  foundCount: '{{count}} found',
  loadingCustomers: 'Loading customers…',
  noDestinationFound: 'No destination found',
  registerWithoutLeavingSale:
    'You can register it without leaving the sale.',
  registerDestination: 'Register destination',
  selectDestination: 'Select a destination',
  createDestinationHint:
    'You can also create a new one to continue with the order.',
  deliveryData: 'Delivery details',
  newCustomerAddress: 'New customer address',
  newDestinationTitle: 'New destination',
  customerAddressReference:
    'Customer {{customer}} · Address {{address}}',
  customerReference: 'Customer {{customer}} · {{name}}',
  addAnotherAddress: 'Add another address for this customer',
  phoneValidation: 'Enter a phone number with 7 to 15 digits.',
  shortInstruction: 'Extension / short instruction',
  recipientName: 'Recipient name',
  nameRequired: 'The name is required.',
  deliveryAddress: 'Delivery address',
  addressRequired: 'The address is required.',
  reference: 'Reference',
  deliveryPrice: 'Delivery price',
  deliveryProductAdded: '{{product}} will be added to the order.',
  configureDeliveryProduct:
    'Configure the delivery charge product first.',
  priceCannotBeNegative: 'The price cannot be negative.',
  identityType: 'Identity type',
  identityNumber: 'Identity number',
  businessNameOrCustomer: 'Business name / customer name',
  fieldRequired: 'This field is required.',
  email: 'Email',
  validEmailRequired: 'Enter a valid email.',
  recentOrders: 'Recent orders',
  deliverySalesHistory: 'Customer delivery sales history',
  loadingHistory: 'Loading history…',
  noDeliverySales: 'There are no delivery sales for this customer yet.',
  productsCount: '{{count}} products',
  continueToOrder: 'Continue to order',
  checkingPrices: 'Checking prices…',
  // General sales tray
  generalSales: 'General sales list',
  allShiftsAndRegisters: 'All shifts and registers',
  includeExpressSales: 'Include express sales',
  searchBy: 'Search by',
  documentType: 'Document type',
  documentNumber: 'Document No.',
  currency: 'Currency',
  state: 'State',
  options: 'Options',
  saleFound: '{{count}} sale found',
  salesFound: '{{count}} sales found',
  fromTotal: 'of {{count}}',
  update: 'Update',
  newSale: 'New sale',
  issueCreditNote: 'Issue credit note',
  pendingUseCase: 'Use case pending implementation',
  saleActions: 'Sale actions',
  noSalesFound:
    'No sales were found for the selected criteria.',
  modifyDocument: 'Modify document',
  modifyPayments: 'Modify payments',
  getPdfAndXml: 'Get PDF and XML',
  reprintDocument: 'Reprint document',
  salesPagination: 'Sales pagination',
  selectDocument: 'Select a document.',
  selectSaleToVoid: 'Select a sale to void.',
  confirmVoidDocument: 'Are you sure you want to void document {{document}}?',
  actionCannotBeUndone: 'This action cannot be undone.',
  yesVoid: 'Yes, void',
  noCancel: 'No, cancel',
  voided: 'Voided',
  documentVoidedSuccessfully: 'The document was voided successfully.',
  couldNotVoidDocument: 'The document could not be voided.',

  // Payment and document issuing
  paymentAndIssueDocument: 'Payment and document issuing',
  documentData: 'Document details',
  series: 'Series',
  number: 'Number',
  customerData: 'Customer details',
  removeCustomerData: 'Remove customer details',
  customerDocumentType: 'Customer document type',
  requiredField: 'This field is required.',
  invalidExpectedFormat: 'Invalid format{{expected}}.',
  expectedFormat: ' — expected: {{mask}}',
  invalidNumberForAmount: 'Invalid number for the current amount.',
  miscellaneousCustomerRule:
    'The business name must be "Cliente Varios" when the document number is 00000001.',
  address: 'Address',
  invalidEmailFormat: 'The email format is incorrect.',
  addCustomerData: 'Add customer details',
  totalToPay: 'Total to pay',
  paidReference: 'of {{symbol}} {{total}} · paid {{symbol}} {{paid}}',
  cashPayments: 'Cash payments',
  exact: 'EXACT',
  automaticCharge: 'Auto-charge',
  exactCashHint:
    'Charge exactly {{symbol}} {{amount}} in cash and close automatically',
  currencyFallback: 'Currency',
  enter: 'Enter',
  entered: 'Entered',
  exchangeRateLabel: 'Exchange rate:',
  cardPayments: 'Card payments',
  card: 'Card',
  authorization: 'Authorization',
  paidAmount: 'Amount',
  tip: 'Tip',
  actions: 'Actions',
  add: 'Add',
  noCardPayments: 'No card payments recorded',
  charge: 'Charge',
  remaining: 'Remaining',
  changeDue: 'Change',
  calculatedTotalMismatch:
    'The calculated amount does not match the register screen. Please try again.',
  totalTimeout: 'The total to pay could not be obtained. The request timed out.',
  system: 'System',
  registerInfoNotFound: 'Register information was not found.',
  selectedDocumentTypeNotFound:
    'The selected document type was not found.',
  getRegisterError: 'Error while loading the register.',
  cardAmountExceedsTotal:
    'The card amount exceeds the amount to pay.',
  enterCardPaymentAmount: 'Enter the amount paid by card.',
  mainCurrency: 'Main currency',
  selectCustomerIdentityType:
    'Select the customer identity document type.',
  enterCustomerIdentityNumber:
    'Enter the customer identity number.',
  enterCustomerBusinessName:
    'Enter the customer name or business name.',
  enterValidCustomerIdentity:
    'Enter a valid customer identity number.',
  enterCustomerAddress: 'Enter the customer address.',
  genericIdentityNameRule:
    'When the identity number is 00000001, the customer name must be "Cliente Varios".',
  genericCustomerIdentityRule:
    'When the customer is "Cliente Varios", the identity number must be 00000001.',
  amountRequiresCustomerIdentity:
    'For this amount, the customer identity document is required.',
  invalidCustomerEmail: 'The email address is invalid.',
  confirmChargeAccount: 'Are you sure you want to charge the account?',
  confirmCreditSale: 'Are you sure you want to record the credit sale?',
  message: 'Message',
  paymentBelowTotal:
    'The payment total is lower than the amount to pay.',
  preferredFormat: 'Which format do you prefer?',
  chooseOption: 'Choose an option',
  ticket: 'Receipt',
  customerNotFound: 'The customer was not found.',
  retrySearchTimeout: 'Search again. The request timed out.',
  amountCalculationError: 'An error occurred while calculating the amounts.',
} as const;

export type TenantTextKey = keyof typeof EN_TEXTS;
export type TenantTextParams = Record<
  string,
  string | number | null | undefined
>;
