import { TenantTextKey } from './tenant-texts.en';

export const ES_TEXTS: Record<TenantTextKey, string> = {
  orderAttendant: 'Personal de sala',
  changeOrderAttendant: 'Cambiar personal de sala',
  selectOrderAttendant: 'Seleccione el personal de sala',
  orderAttendantRequired: 'Debe seleccionar el personal de sala.',
  onlyAdminCanChangeOrderAttendant:
    'Solo el administrador puede cambiar el personal de sala.',
  couldNotChangeOrderAttendant:
    'No se pudo cambiar el personal de sala.',
  unexpectedOrderAttendantChangeError:
    'Ocurrió un error al cambiar el personal de sala.',

  accept: 'Aceptar',
  cancel: 'Cancelar',
  close: 'Cerrar',
  closeDialog: 'Cerrar diálogo',
  delete: 'Eliminar',
  error: 'Error',
  validation: 'Validación',
  exit: 'Salir',
  search: 'Buscar',
  retry: 'Reintentar',
  save: 'Guardar',
  saving: 'Guardando…',
  openStatus: 'ABIERTO',
  closedStatus: 'CERRADO',
  language: 'Idioma',
  useTenantLanguage: 'Usar idioma del negocio',
  cultureChangeError: 'No se pudo cambiar la preferencia de idioma.',

  restaurantManagement:
    'Gestión ágil para restaurantes y hostelería',
  installApplication: 'Instalar aplicación',
  invalidCredentials:
    'Usuario o contraseña incorrectos. Inténtalo de nuevo.',
  branch: 'Sucursal',
  user: 'Usuario',
  usernamePlaceholder: 'Ingresa tu usuario',
  password: 'Contraseña',
  passwordPlaceholder: 'Ingresa tu contraseña',
  showPassword: 'Mostrar contraseña',
  hidePassword: 'Ocultar contraseña',
  numericKeypad: 'Teclado numérico',
  signIn: 'Entrar',
  signingIn: 'Ingresando…',
  forgotPassword: '¿Olvidaste tu contraseña?',
  checkYourEmail: 'Revisa tu email',
  resetEmailSentPrefix: 'Si el usuario',
  resetEmailSentSuffix:
    'tiene un email registrado, recibirás un enlace para restablecer tu contraseña en los próximos minutos.',
  backToLogin: 'Volver al inicio de sesión',
  back: 'Volver',
  recoverPassword: 'Recuperar contraseña',
  recoverPasswordHint:
    'Te enviaremos un enlace a tu email registrado.',
  usernameNamePlaceholder: 'Ingresa tu nombre de usuario',
  sendInstructions: 'Enviar instrucciones',
  sending: 'Enviando…',
  applicationVersion: 'Versión de la aplicación',
  serverOffline: 'Sin conexión con el servidor',
  operationsUnavailable: 'las operaciones no están disponibles',
  enterPassword: 'Ingresar contraseña',
  noBusinessRole:
    'El usuario no tiene un rol de negocio asignado en Keycloak.',
  couldNotLoadStations: 'No se pudo obtener la lista de estaciones.',
  stationNotConfigured: 'Estación no configurada',
  stationIdentifierMissing:
    'Este dispositivo no tiene un identificador de estación. Contacta al administrador.',
  selectBranchAndUser: 'Selecciona una sucursal e ingresa tu usuario.',
  iosInstallHint:
    'Para instalar la aplicación en iOS, abre el menú de compartir y selecciona "Agregar a la pantalla de inicio".',
  couldNotLoadTenants: 'No se pudo obtener la lista de tenants.',
  noTenantsAvailable:
    'No hay tenants disponibles. Contacta al administrador.',
  couldNotLoadTenantsRetry:
    'No se pudieron cargar los tenants. Inténtalo nuevamente.',

  openMenu: 'Abrir menú',
  restaurant: 'Restaurante',
  shift: 'Turno',
  noShift: 'Sin turno',
  shiftSales: 'Venta turno',
  orders: 'Pedidos',
  averageTicket: 'Ticket medio',
  home: 'Inicio',
  logout: 'Salir',
  dashboard: 'Dashboard',
  administration: 'Administración',
  register: 'Caja',
  noOpenShiftForStation:
    'No hay un turno abierto para esta estación',
  componentWillClose: 'Esta pantalla se cerrará.',
  change: 'Cambiar',

  goToAdministration: 'Ir a Administración',
  administrationShortcut: 'Administración (Ctrl+Alt+A)',
  date: 'Fecha',
  tableChannel: 'CANAL MESA',
  takeawayChannel: 'CANAL LLEVAR',
  deliveryChannel: 'CANAL DELIVERY',
  admission: 'ENTRADA',
  refresh: 'ACTUALIZAR',
  orderNumber: 'Pedido N.º',
  delivery: 'Entrega',
  phone: 'Teléfono',
  customer: 'Cliente',
  order: 'Pedido',
  product: 'Producto',
  observation: 'Observación',
  hostess: 'Anfitriona',
  couponNumber: 'N.º cupón',
  withComplement: 'Con complemento',
  price: 'Precio',
  quantity: 'Cant.',
  increaseQuantity: 'Aumentar cantidad',
  decreaseQuantity: 'Restar cantidad',
  moreOptions: 'Más opciones',
  moveToAnotherTable: 'Trasladar a otra mesa',
  courtesyDrink: 'Trago de cortesía',
  amount: 'Importe',
  discount: 'Descuento',
  removeDiscount: 'Quitar descuento',
  total: 'Total',
  bagTax: 'Bolsa',
  preBill: 'Precuenta',
  issuedDocuments: 'Documentos emitidos',
  expensesReports: 'Gastos / Reportes',
  combo: 'Combo',
  viewComplements: 'Ver complementos',
  viewComplement: 'Ver complemento',
  express: 'Express',
  sendOrder: 'Enviar pedido',
  lock: 'Bloquear',
  reset: 'Rehacer',
  prioritizeDispatch: 'Priorizar despacho',
  cancelOrder: 'Anular pedido',
  reprint: 'Reimprimir',
  mergeTablePrefix: 'se unirá a la mesa que seleccione',
  occupiedTablesOnly: 'solo se muestran mesas ocupadas',
  selectFreeTableForOrder:
    'Seleccione una mesa libre para trasladar el pedido',
  selectDestinationTable: 'Seleccione la mesa destino para',
  verifyBackend:
    'Verifica que el backend esté activo y vuelve a intentarlo.',
  newOrder: 'Nuevo pedido',
  processOrder: 'Procesar pedido',
  moveToTable: 'Trasladar a mesa',
  changeSpace: 'Cambiar espacio',
  mergeAccount: 'Unir cuenta',
  splitAccount: 'Dividir cuenta',
  activateSpace: 'Activar espacio',
  searchProducts: 'Buscar productos',
  selectSpace: 'Debe seleccionar un espacio.',
  mergeSpace: 'Unir espacio',
  changeSpaceTitle: 'Cambiar espacio',
  customerNamePlaceholder: 'Ingrese el nombre del cliente',
  courtesyCodeEntered: 'Código de cortesía ingresado',
  enteredCode: 'El código ingresado es: {{code}}',
  deleteCode: 'Eliminar código',
  keepCode: 'Mantener código',
  codeDeleted: 'Código eliminado',
  enterCourtesyCode: 'Ingresar código de cortesía',
  enterHostessCodes: 'Ingresar códigos de anfitrionas',
  codeLabel: 'Código {{number}}',
  addMore: 'Agregar más',
  enterHostessCode: 'Ingresar código de anfitriona {{number}}',
  orderNotFound: 'No existe el pedido.',
  productTransfer: 'Traslado de producto',
  selectTable: 'Debe seleccionar una mesa.',
  transferToTable: 'Trasladar a mesa',
  selectOrder: 'Debe seleccionar un pedido.',
  couldNotMoveOrder: 'No se pudo trasladar el pedido.',
  errorMovingOrder: 'Ocurrió un error al trasladar el pedido.',
  couldNotTransferProduct: 'No se pudo realizar el traslado.',
  errorMovingProduct: 'Ocurrió un error al trasladar el producto.',
  enterGuestCount: 'Ingrese N.º de personas',
  positiveNumberRequired: 'Ingrese un número válido mayor que cero.',
  orderNotFoundInSpace: 'No existe el pedido en este espacio.',
  unexpectedError: 'Algo salió mal',
  addQuantityFirst: 'Agregue primero la cantidad.',
  confirmDeleteProduct: '¿Está seguro de eliminar {{product}}?',
  enterAdministratorCode: 'Ingresar código de administrador',
  invalidCode: 'Código inválido',
  incorrectCode: 'El código ingresado no es correcto.',
  enterPrice: 'Ingresar precio',
  confirmVoidSpaceOrder:
    '¿Está seguro de anular el pedido de {{space}}?',
  processOrderTitle: 'Procesar pedido',
  confirmRemoveDiscount: '¿Está seguro de quitar el descuento?',
  yes: 'Sí',
  no: 'No',
  orderNotFoundInAccount: 'No existe el pedido en la cuenta.',
  printPreBill: 'Imprimir precuenta',
  noProductsEntered: 'No ha ingresado ningún producto.',
  allProductsMustBeSaved:
    'No se guardaron todos los productos de la lista.',
  orderMustBeSaved: 'Debe tener todo el pedido guardado.',
  internalErrorRefresh: 'Error interno. Actualice la pantalla.',

  closeShift: 'Cerrar turno',
  shiftNumber: 'N.º de turno',
  startDate: 'Fecha de inicio',
  currentDate: 'Fecha actual',
  exchangeRate: 'Tipo de cambio',
  status: 'Estado',
  shiftClosed: 'TURNO CERRADO',
  selectOpenShiftRegister:
    'Selecciona una caja con un turno abierto para cerrarlo.',
  partialClose: 'Cierre parcial',
  partialCloseHint:
    'Omite la validación de pedidos pendientes de cobrar.',
  pendingOrdersTitle: 'Pedidos pendientes de cobrar ({{count}})',
  pendingOrdersExplanation:
    'Estos pedidos impiden cerrar el turno. Puedes anularlos aquí o salir para cobrarlos desde Ventas. Después vuelve a intentar el cierre.',
  account: 'Cuenta',
  spaceOrChannel: 'Espacio / canal',
  void: 'Anular',
  revalidateClose: 'Revalidar cierre',
  openShift: 'Aperturar turno',
  shiftOpened: 'Turno {{number}} abierto',
  registerAlreadyOperational:
    'La caja seleccionada ya está operativa. No es necesario volver a aperturarla.',
  selectRegister: 'Seleccione una caja.',
  enterExchangeRate: 'Ingrese el tipo de cambio.',
  enterPositiveValue: 'Ingrese un valor mayor que cero.',
  workDate: 'Fecha de trabajo',
  openAction: 'Aperturar',
  noOpenShiftForRegister: 'No hay un turno abierto para esta caja.',
  couldNotCloseShift: 'No se pudo cerrar el turno.',
  shiftCloseTitle: 'Cierre de turno',
  shiftClosedSuccessfully: 'El turno se cerró correctamente.',
  voidOrderTitle: 'Anular pedido N.º {{number}}',
  voidOrderWarning:
    'Esta operación anulará el pedido completo y no puede deshacerse.',
  voidReason: 'Motivo de la anulación',
  enterVoidReason: 'Ingrese el motivo...',
  voidOrder: 'Anular pedido',
  voidReasonRequired: 'Debe ingresar el motivo de la anulación.',
  couldNotVoidOrder: 'No se pudo anular el pedido.',
  orderVoided: 'Pedido anulado',
  orderVoidedSuccessfully: 'El pedido se anuló correctamente.',
  unpaidSalesTitle: 'Ventas sin pago registrado',
  unpaidSalesQuestion:
    'Existen ventas sin pago registrado. ¿Son ventas al crédito?',
  document: 'Documento',
  confirmCreditSales: 'Sí, son al crédito',
  shiftOpenedTitle: 'Turno aperturado',
  registerAvailableForOperations:
    'La caja ya está disponible para registrar operaciones.',

  newDelivery: 'Nuevo delivery',
  chooseDeliveryOrigin:
    'Elige cómo se recibió el pedido antes de identificar al cliente.',
  businessPartnersCount: '{{count}} socios de negocio',
  deliveryMode: 'Modalidad de delivery',
  phoneDelivery: 'Delivery por teléfono',
  phoneDeliveryHint:
    'Busca o registra el teléfono y la dirección del cliente.',
  businessPartnerOrder: 'Pedido de un socio de negocio',
  businessPartnerExamples:
    'Glovo, Uber Eats u otra plataforma con precios propios.',
  noBusinessPartners: 'No hay socios de negocio configurados.',
  selectDeliveryMode: 'Selecciona una modalidad para continuar',
  selectDeliveryModeHint:
    'Así el pedido conservará correctamente su origen y sus reglas de precio.',
  externalOrderData: 'Datos del pedido externo',
  noPhoneRecordForExternalOrder:
    'No se crea una ficha telefónica para este pedido',
  businessPartner: 'Socio de negocio',
  selectOriginBusinessPartner:
    'Selecciona el socio de negocio que originó el pedido.',
  customerName: 'Nombre del cliente',
  customerNameRequired: 'El nombre del cliente es obligatorio.',
  unnamedCustomer: 'Sin nombre',
  businessPartnerPricesHint:
    'Al continuar se aplicarán los precios configurados para el socio. Si un producto no tiene precio especial, conservará su precio normal.',
  deliverySearchLabel: 'Teléfono, cliente, documento o dirección',
  clearSearch: 'Limpiar búsqueda',
  newDestination: 'Nuevo destino',
  destinationsFound: 'Destinos encontrados',
  destinations: 'Destinos',
  foundCount: '{{count}} encontrados',
  loadingCustomers: 'Consultando clientes…',
  noDestinationFound: 'No encontramos un destino',
  registerWithoutLeavingSale:
    'Puedes registrarlo sin abandonar la venta.',
  registerDestination: 'Registrar destino',
  selectDestination: 'Selecciona un destino',
  createDestinationHint:
    'También puedes crear uno nuevo para continuar con el pedido.',
  deliveryData: 'Datos de entrega',
  newCustomerAddress: 'Nueva dirección del cliente',
  newDestinationTitle: 'Nuevo destino',
  customerAddressReference:
    'Cliente {{customer}} · Dirección {{address}}',
  customerReference: 'Cliente {{customer}} · {{name}}',
  addAnotherAddress: 'Agregar otra dirección a este cliente',
  phoneValidation: 'Ingresa un teléfono de 7 a 15 dígitos.',
  shortInstruction: 'Anexo / indicación corta',
  recipientName: 'Nombre de quien recibe',
  nameRequired: 'El nombre es obligatorio.',
  deliveryAddress: 'Dirección de entrega',
  addressRequired: 'La dirección es obligatoria.',
  reference: 'Referencia',
  deliveryPrice: 'Precio del delivery',
  deliveryProductAdded: 'Se agregará {{product}} al pedido.',
  configureDeliveryProduct:
    'Configura primero el producto de cargo por delivery.',
  priceCannotBeNegative: 'El precio no puede ser negativo.',
  identityType: 'Tipo de identidad',
  identityNumber: 'Número de identidad',
  businessNameOrCustomer: 'Razón social / nombre del cliente',
  fieldRequired: 'Este campo es obligatorio.',
  email: 'Correo',
  validEmailRequired: 'Ingresa un correo válido.',
  recentOrders: 'Últimos pedidos',
  deliverySalesHistory: 'Historial de ventas delivery del cliente',
  loadingHistory: 'Consultando historial…',
  noDeliverySales:
    'Aún no hay ventas delivery asociadas a este cliente.',
  productsCount: '{{count}} productos',
  continueToOrder: 'Continuar al pedido',
  checkingPrices: 'Consultando precios…',
  generalSales: 'Listado de ventas generales',
  allShiftsAndRegisters: 'Todos los turnos y cajas',
  includeExpressSales: 'Incluir ventas express',
  searchBy: 'Buscar por',
  documentType: 'Tipo de documento',
  documentNumber: 'N.º doc.',
  currency: 'Moneda',
  state: 'Estado',
  options: 'Opciones',
  saleFound: '{{count}} venta encontrada',
  salesFound: '{{count}} ventas encontradas',
  fromTotal: 'de {{count}}',
  update: 'Actualizar',
  newSale: 'Nueva venta',
  issueCreditNote: 'Emitir nota de crédito',
  pendingUseCase: 'Caso de uso pendiente de implementar',
  saleActions: 'Acciones de la venta',
  noSalesFound:
    'No se encontraron ventas con los criterios seleccionados.',
  modifyDocument: 'Modificar documento',
  modifyPayments: 'Modificación de pagos',
  getPdfAndXml: 'Obtener PDF y XML',
  reprintDocument: 'Reimprimir documento',
  salesPagination: 'Paginación de ventas',
  selectDocument: 'Seleccione un documento.',
  selectSaleToVoid: 'Debe seleccionar una venta para anular.',
  confirmVoidDocument:
    '¿Está seguro de anular el documento {{document}}?',
  actionCannotBeUndone: 'Esta acción no se puede deshacer.',
  yesVoid: 'Sí, anular',
  noCancel: 'No, cancelar',
  voided: 'Anulado',
  documentVoidedSuccessfully: 'El documento se anuló con éxito.',
  couldNotVoidDocument: 'No se pudo anular el documento.',
  paymentAndIssueDocument: 'Pago y emisión de comprobante',
  documentData: 'Datos del comprobante',
  series: 'Serie',
  number: 'Número',
  customerData: 'Datos del cliente',
  removeCustomerData: 'Quitar datos del cliente',
  customerDocumentType: 'Tipo de documento del cliente',
  requiredField: 'El campo es requerido.',
  invalidExpectedFormat: 'Formato inválido{{expected}}.',
  expectedFormat: ' — esperado: {{mask}}',
  invalidNumberForAmount: 'Número inválido para el monto actual.',
  miscellaneousCustomerRule:
    'La razón social debe ser "Cliente Varios" cuando el documento es 00000001.',
  address: 'Dirección',
  invalidEmailFormat: 'El formato del correo es incorrecto.',
  addCustomerData: 'Añadir datos del cliente',
  totalToPay: 'Total a pagar',
  paidReference: 'de {{symbol}} {{total}} · pagado {{symbol}} {{paid}}',
  cashPayments: 'Pagos en efectivo',
  exact: 'EXACTO',
  automaticCharge: 'Auto-cobra',
  exactCashHint:
    'Cobra {{symbol}} {{amount}} exacto en efectivo y cierra automáticamente',
  currencyFallback: 'Moneda',
  enter: 'Ingresar',
  entered: 'Ingresado',
  exchangeRateLabel: 'Tipo de cambio:',
  cardPayments: 'Pagos con tarjeta',
  card: 'Tarjeta',
  authorization: 'Autorización',
  paidAmount: 'Monto',
  tip: 'Propina',
  actions: 'Acciones',
  add: 'Agregar',
  noCardPayments: 'Sin pagos con tarjeta registrados',
  charge: 'Cobrar',
  remaining: 'Falta',
  changeDue: 'Vuelto',
  calculatedTotalMismatch:
    'El monto calculado no coincide con el que muestra la pantalla de caja. Vuelva a intentarlo.',
  totalTimeout:
    'No se pudo obtener el total a pagar. Se agotó el tiempo de espera.',
  system: 'Sistema',
  registerInfoNotFound: 'No se encontró información de la caja.',
  selectedDocumentTypeNotFound:
    'No se encontró el tipo de documento seleccionado.',
  getRegisterError: 'Error al obtener la caja.',
  cardAmountExceedsTotal:
    'El monto de tarjeta sobrepasa el monto a pagar.',
  enterCardPaymentAmount: 'Ingrese el monto pagado con tarjeta.',
  mainCurrency: 'Moneda principal',
  selectCustomerIdentityType:
    'Seleccione el tipo de documento del cliente.',
  enterCustomerIdentityNumber:
    'Ingrese el número de identificación del cliente.',
  enterCustomerBusinessName:
    'Ingrese el nombre o razón social del cliente.',
  enterValidCustomerIdentity:
    'Ingrese correctamente el número de identificación del cliente.',
  enterCustomerAddress: 'Ingrese la dirección del cliente.',
  genericIdentityNameRule:
    'Si el número de identidad es 00000001, el nombre del cliente debe ser "Cliente Varios".',
  genericCustomerIdentityRule:
    'Si el cliente es "Cliente Varios", el número de identidad debe ser 00000001.',
  amountRequiresCustomerIdentity:
    'Para este importe debe ingresar el documento de identidad del cliente.',
  invalidCustomerEmail: 'El correo electrónico está mal ingresado.',
  confirmChargeAccount: '¿Está seguro de cobrar la cuenta?',
  confirmCreditSale: '¿Está seguro de registrar la venta al crédito?',
  message: 'Mensaje',
  paymentBelowTotal:
    'El total de pago es menor que el monto a pagar.',
  preferredFormat: '¿Qué formato prefiere?',
  chooseOption: 'Elija una opción',
  ticket: 'Ticket',
  customerNotFound: 'No se encontró el cliente.',
  retrySearchTimeout:
    'Vuelva a realizar la búsqueda. Se agotó el tiempo de espera.',
  amountCalculationError: 'Ocurrió un error al calcular los montos.',
  description: 'Descripción',
  descriptionRequired: 'La descripción es requerida.',
  required: 'Requerido.',
  updateAction: 'Actualizar',
  edit: 'Editar',
  active: 'Activo',
  inactive: 'Inactivo',
  family: 'Familia',
  familyRequired: 'La familia es requerida.',
  searchByDescription: 'Buscar por descripción',
  descriptionOrStatus: 'Descripción, estado...',
  maintenanceFamilies: 'Mantenimiento de familias',
  newFamily: 'Nueva familia',
  maintenanceSubfamilies: 'Mantenimiento de subfamilias',
  newSubfamily: 'Nueva subfamilia',
  productGroups: 'Grupos de productos',
  newGroup: 'Nuevo grupo',
  maintenancePrintAreas: 'Mantenimiento de áreas de impresión',
  newPrintArea: 'Nueva área',
  descriptionOrPrinter: 'Descripción o impresora...',
  printerName: 'Nombre de impresora',
  printerExample: 'Ej. EPSON_TM20, HP_LaserJet...',
  maintenanceColors: 'Mantenimiento de colores',
  newColor: 'Nuevo color',
  descriptionOrRgb: 'Descripción o RGB',
  color: 'Color',
  chooseColor: 'Elegir color',
  maintenanceStations: 'Mantenimiento de estaciones',
  newStation: 'Nueva estación',
  searchStation: 'Buscar por nombre o identificador único',
  uniqueIdentifier: 'Identificador único',
  type: 'Tipo',
  stationType: 'Tipo de estación',
  assignedRegister: 'Caja asignada',
  maintenanceEnvironments: 'Mantenimiento de ambientes',
  newEnvironment: 'Nuevo ambiente',
  searchEnvironment: 'Buscar por descripción, estado o posición',
  position: 'Posición',
  selectState: 'Seleccione un estado.',
  selectPosition: 'Seleccione una posición (1 a 10)',
  choosePosition: 'Elegir posición (1 × 10)',
  maintenanceObservations: 'Mantenimiento de observaciones',
  newObservation: 'Nueva observación',
  descriptionTypePosition: 'Descripción, tipo, posición...',
  observationExample: 'Ej. BIEN CALIENTE, SALSA APARTE, ...',
  selectGridPosition:
    'Seleccione la posición ({{rows}} x {{cols}}) — Tipo: {{type}}',
  selected: 'Seleccionada',
  occupied: 'Ocupada',
  free: 'Libre',
  maintenanceEmployees: 'Mantenimiento de empleados',
  newEmployee: 'Nuevo empleado',
  searchEmployee: 'Buscar por nombre, documento de identidad, etc.',
  name: 'Nombre',
  identityDocument: 'Documento de identidad',
  identityRequired: 'El documento de identidad es requerido.',
  nameRequiredField: 'El nombre es requerido.',
  addressRequiredField: 'La dirección es requerida.',
  telephone: 'Teléfono',
  validPhoneRequired: 'Introduzca un teléfono válido.',

  // Mantenimiento de cajas
  maintenanceRegisters: 'Mantenimiento de cajas',
  newRegister: 'Nueva caja',
  searchRegister: 'Descripción, default...',
  defaultRegister: 'Caja por defecto',
  salesChannel: 'Canal de venta',
  enabledSalesChannels: 'Canales de venta habilitados',
  defaultSalesChannel: 'Canal de venta por defecto',
  selectAtLeastOneChannel: 'Selecciona al menos un canal arriba.',
  emitsPreBill: 'Emite precuenta',
  emitsKitchenTicket: 'Emite comanda',
  emitsDiscount: 'Emite descuento',
  allowsSplitOrder: 'Permite dividir pedido',
  allowsPartialClose: 'Permite cierre parcial',
  onlineElectronicSubmission: 'Envío electrónico online',
  automaticDeliveryPreBill: 'Precuenta delivery automática',
  allowTaxiPayments: 'Permitir pago a taxistas',

  // Mantenimiento de descuentos
  maintenanceDiscounts: 'Mantenimiento de descuentos',
  newDiscount: 'Nuevo descuento',
  searchDiscount: 'Descripción, tipo...',
  percentage: 'Porcentaje',
  clickToActivate: 'Clic para activar',
  clickToDeactivate: 'Clic para desactivar',
  noDiscountsRegistered: 'Sin descuentos registrados.',
  editDiscount: 'Editar descuento',
  discountType: 'Tipo de descuento',
  selectType: 'Seleccione un tipo.',
  enterPercentageGreaterThanZero: 'Ingresa un porcentaje mayor a 0.',
  valeTypeNoPercentage: 'El tipo Vale no requiere porcentaje.',

  // Mantenimiento de clientes
  maintenanceCustomers: 'Mantenimiento de clientes',
  newCustomer: 'Nuevo cliente',
  searchCustomer: 'Buscar por nombre, RUC, etc.',
  businessName: 'Razón social',
  businessNameRequired: 'La razón social es requerida.',

  // Mantenimiento de productos
  maintenanceProducts: 'Mantenimiento de productos',
  newProduct: 'Nuevo producto',
  searchProduct: 'Nombre, descripción, precio, posición...',
  shortName: 'Nombre corto',
  visible: 'Visible',
  productTypeMenuCard: 'Carta',
  productTypeMenu: 'Menú',
  productTypeWithComplements: 'Con complementos',
  productTypeComplement: 'Complemento',
  subfamily: 'Subfamilia',
  group: 'Grupo',
  menuSection: 'Sección de menú',
  requiredForMenu: 'Requerido para Menú.',
  complementsQuantity: 'Cantidad de complementos',
  requiredForType2: 'Requerido para Tipo=2.',
  complementFactor: 'Factor complemento',
  complementFactorHint: '> 0 (2 decimales).',
  complementPosition: 'Posición complemento',
  selectPosition6x5: 'Seleccione posición 6×5',
  choosePosition6x5: 'Elegir posición (6×5)',
  selectPosition8x9: 'Seleccione posición 8×9',
  choosePosition8x9: 'Elegir posición (8×9)',
  minimumPrice: 'Precio mínimo',
  requiredIfNoPrice: 'Requerido si "Sin precio".',
  idAndClassification: 'Identificación y clasificación',
  configAndPrintAreas: 'Configuración y áreas de impresión',
  tax: 'Impuesto',
  noPrice: 'Sin precio',
  exclusiveHostess: 'Exclusivo anfitriona',
  allowsCourtesyDrink: 'Permite trago cortesía',
  printAreas: 'Áreas de impresión',
  printAreasHint: 'Selecciona una o varias áreas donde se imprimirá la comanda de este producto.',
  invalidPrice: 'Precio inválido.',

  // Mantenimiento de socios de negocio
  maintenanceBusinessPartners: 'Mantenimiento de socios de negocio',
  newBusinessPartner: 'Nuevo socio',
  searchBusinessPartner: 'Buscar socio',
  commission: 'Comisión',
  configuredPrices: 'Precios configurados',
  editPartnerAndPrices: 'Editar socio y precios',
  deleteBusinessPartner: 'Eliminar socio',
  loadingBusinessPartners: 'Cargando socios…',
  businessPartnerName: 'Nombre del socio de negocio',
  businessPartnerNameRequired: 'El nombre del socio es obligatorio.',
  mustBeBetween0And100: 'Debe estar entre 0 y 100.',
  partnerActiveForDelivery: 'Socio activo para delivery',
  specialProductPrices: 'Precios especiales por producto',
  normalPrice: 'Precio normal',
  partnerPrice: 'Precio del socio',
  useNormalPrice: 'Usar precio normal',
  noProductsMatchSearch: 'No hay productos que coincidan con la búsqueda.',
  saveBusinessPartner: 'Guardar socio',
  backToList: 'Volver al listado',

  // Mantenimiento de espacios
  maintenanceSpaces: 'Mantenimiento de espacios',
  newSpace: 'Nuevo espacio',
  searchSpace: 'Buscar por descripción, número, posición o ambiente',
  environment: 'Ambiente',
  selectEnvironment: 'Seleccione un ambiente.',
  numberRequiredGreaterThanZero: 'El número es requerido y debe ser mayor a 0.',
  selectPositionSimple: 'Seleccione una posición',
  choosePositionSimple: 'Elegir posición',
  selectIfActive: 'Seleccione si está activo.',
  selectIfVisible: 'Seleccione si es visible.',

  // Mantenimiento de usuarios
  maintenanceUsers: 'Mantenimiento de usuarios',
  newUser: 'Nuevo usuario',
  searchUser: 'Buscar por nombre de usuario, nivel de usuario, etc.',
  username: 'Nombre de usuario',
  level: 'Nivel',
  usernameRequired: 'El nombre de usuario es requerido.',
  passwordRequired: 'La contraseña es requerida.',
  employee: 'Empleado',
  selectValidEmployee: 'Seleccione un empleado válido.',
  selectRole: 'Seleccione un cargo.',
  changePassword: 'Cambiar contraseña',
  cancelChange: 'Cancelar cambio',
  currentPassword: 'Contraseña actual',
  newPassword: 'Nueva contraseña',
  confirmPassword: 'Confirmar contraseña',
  passwordsDoNotMatch: 'Las contraseñas no coinciden',
  savePassword: 'Guardar contraseña',

  // Diálogos pequeños (mcant, mtext, delete-product, mozo)
  switchToNumeric: 'Cambiar a numérico',
  switchToLetters: 'Cambiar a letras',
  clear: 'Borrar',
  confirmVoidTitle: 'Confirmar anulación',
  administrator: 'Administrador',
  authenticate: 'Autenticar',
  tableData: 'Datos de mesa',
  tableNumber: 'N.° de mesa',
  guests: 'N.° de personas',
  onlyNumbers: 'Solo números',
  observations: 'Observaciones',
  writeManualObservation: 'Escribir observación manual',
  food: 'Comidas',
  drinks: 'Bebidas',
  selectPositionTitle: 'Seleccionar posición',
};

export const ES_PE_OVERRIDES: Partial<Record<TenantTextKey, string>> = {
  orderAttendant: 'Mozo',
  changeOrderAttendant: 'Cambiar mozo',
  selectOrderAttendant: 'Seleccione un mozo',
  orderAttendantRequired: 'Debe seleccionar un mozo.',
  onlyAdminCanChangeOrderAttendant:
    'Solo el administrador puede cambiar el mozo.',
  couldNotChangeOrderAttendant: 'No se pudo cambiar el mozo.',
  unexpectedOrderAttendantChangeError:
    'Ocurrió un error al cambiar el mozo.',
};

export const ES_ES_OVERRIDES: Partial<Record<TenantTextKey, string>> = {
  orderAttendant: 'Camarero',
  changeOrderAttendant: 'Cambiar camarero',
  selectOrderAttendant: 'Seleccione un camarero',
  orderAttendantRequired: 'Debe seleccionar un camarero.',
  onlyAdminCanChangeOrderAttendant:
    'Solo el administrador puede cambiar el camarero.',
  couldNotChangeOrderAttendant: 'No se pudo cambiar el camarero.',
  unexpectedOrderAttendantChangeError:
    'Ocurrió un error al cambiar el camarero.',
};
