import { TenantTextKey } from './tenant-texts.en';

export const ES_TEXTS: Record<TenantTextKey, string> = {
  orderAttendant: 'Personal de sala',
  changeOrderAttendant: 'Cambiar personal de sala',
  selectOrderAttendant: 'Seleccione el personal de sala',
  orderAttendantRequired: 'Debe seleccionar el personal de sala.',
  onlyAdminCanChangeOrderAttendant:
    'Solo el administrador puede cambiar el personal de sala.',
  couldNotChangeOrderAttendant:
    'No se pudo cambiar el personal de sala.',
  unexpectedOrderAttendantChangeError:
    'Ocurrió un error al cambiar el personal de sala.',

  accept: 'Aceptar',
  cancel: 'Cancelar',
  close: 'Cerrar',
  closeDialog: 'Cerrar diálogo',
  delete: 'Eliminar',
  error: 'Error',
  validation: 'Validación',
  saved: 'Guardado',
  deleted: 'Eliminado',
  yesDelete: 'Sí, eliminar',
  exit: 'Salir',
  search: 'Buscar',
  retry: 'Reintentar',
  save: 'Guardar',
  saving: 'Guardando…',
  openStatus: 'ABIERTO',
  closedStatus: 'CERRADO',
  language: 'Idioma',
  useTenantLanguage: 'Usar idioma del negocio',
  cultureChangeError: 'No se pudo cambiar la preferencia de idioma.',
  showNavigationHeader: 'Mostrar navegación',
  hideNavigationHeader: 'Ocultar navegación',

  stationAssistantEyebrow: 'Configuración rápida',
  stationAssistantTitle: '¿Quieres configurar este ordenador?',
  stationAssistantBody:
    'Hay estaciones disponibles sin dispositivo asociado: {{options}}.',
  stationAssistantConfigure: 'Configurar ahora',
  stationAssistantLater: 'Preguntarme después',
  stationAssistantNever: 'No volver a mostrar',
  stationAssistantChooseTitle: '¿Para qué se utilizará este ordenador?',
  stationAssistantChooseBody:
    'Solo aparecen los tipos de estación que están disponibles en este momento.',
  stationAssistantRegisterOption: 'Estación de caja',
  stationAssistantAttendantOption: 'Estación de {{attendant}}',
  stationAssistantAssigning: 'Vinculando estación…',
  stationAssistantTaken:
    'Otro dispositivo acaba de vincular esa estación. Hemos actualizado las opciones disponibles.',
  stationAssistantError:
    'No se pudo vincular este ordenador. Inténtalo nuevamente.',
  stationAssistantReady: '{{station}} ya está vinculada a este ordenador.',

  restaurantManagement:
    'Gestión ágil para restaurantes y hostelería',
  installApplication: 'Instalar aplicación',
  invalidCredentials:
    'Usuario o contraseña incorrectos. Inténtalo de nuevo.',
  branch: 'Sucursal',
  user: 'Usuario',
  usernamePlaceholder: 'Ingresa tu usuario',
  password: 'Contraseña',
  passwordPlaceholder: 'Ingresa tu contraseña',
  showPassword: 'Mostrar contraseña',
  hidePassword: 'Ocultar contraseña',
  numericKeypad: 'Teclado numérico',
  signIn: 'Entrar',
  signingIn: 'Ingresando…',
  forgotPassword: '¿Olvidaste tu contraseña?',
  checkYourEmail: 'Revisa tu email',
  resetEmailSentPrefix: 'Si el usuario',
  resetEmailSentSuffix:
    'tiene un email registrado, recibirás un enlace para restablecer tu contraseña en los próximos minutos.',
  backToLogin: 'Volver al inicio de sesión',
  back: 'Volver',
  recoverPassword: 'Recuperar contraseña',
  recoverPasswordHint:
    'Te enviaremos un enlace a tu email registrado.',
  usernameNamePlaceholder: 'Ingresa tu nombre de usuario',
  sendInstructions: 'Enviar instrucciones',
  sending: 'Enviando…',
  applicationVersion: 'Versión de la aplicación',
  serverOffline: 'Sin conexión con el servidor',
  operationsUnavailable: 'las operaciones no están disponibles',
  enterPassword: 'Ingresar contraseña',
  noBusinessRole:
    'El usuario no tiene un rol de negocio asignado en Keycloak.',
  couldNotLoadStations: 'No se pudo obtener la lista de estaciones.',
  stationNotConfigured: 'Estación no configurada',
  stationIdentifierMissing:
    'Este dispositivo no tiene un identificador de estación. Contacta al administrador.',
  selectBranchAndUser: 'Selecciona una sucursal e ingresa tu usuario.',
  iosInstallHint:
    'Para instalar la aplicación en iOS, abre el menú de compartir y selecciona "Agregar a la pantalla de inicio".',
  couldNotLoadTenants: 'No se pudo obtener la lista de tenants.',
  noTenantsAvailable:
    'No hay tenants disponibles. Contacta al administrador.',
  couldNotLoadTenantsRetry:
    'No se pudieron cargar los tenants. Inténtalo nuevamente.',

  openMenu: 'Abrir menú',
  restaurant: 'Restaurante',
  shift: 'Turno',
  noShift: 'Sin turno',
  shiftSales: 'Venta turno',
  orders: 'Pedidos',
  averageTicket: 'Ticket medio',
  home: 'Inicio',
  logout: 'Salir',
  dashboard: 'Dashboard',
  administration: 'Administración',
  register: 'Caja',
  noOpenShiftForStation:
    'No hay un turno abierto para esta estación',
  componentWillClose: 'Esta pantalla se cerrará.',
  change: 'Cambiar',

  date: 'Fecha',
  tableChannel: 'CANAL MESA',
  takeawayChannel: 'CANAL LLEVAR',
  deliveryChannel: 'CANAL DELIVERY',
  admission: 'ENTRADA',
  refresh: 'ACTUALIZAR',
  orderNumber: 'Pedido N.º',
  delivery: 'Entrega',
  phone: 'Teléfono',
  customer: 'Cliente',
  order: 'Pedido',
  product: 'Producto',
  observation: 'Observación',
  hostess: 'Anfitriona',
  couponNumber: 'N.º cupón',
  withComplement: 'Con complemento',
  price: 'Precio',
  quantity: 'Cant.',
  increaseQuantity: 'Aumentar cantidad',
  decreaseQuantity: 'Restar cantidad',
  moreOptions: 'Más opciones',
  moveToAnotherTable: 'Trasladar a otra mesa',
  courtesyDrink: 'Trago de cortesía',
  amount: 'Importe',
  discount: 'Descuento',
  removeDiscount: 'Quitar descuento',
  total: 'Total',
  bagTax: 'Bolsa',
  preBill: 'Precuenta',
  issuedDocuments: 'Documentos emitidos',
  expensesReports: 'Gastos / Reportes',
  combo: 'Menú',
  viewComplements: 'Ver complementos',
  viewComplement: 'Ver complemento',
  express: 'Express',
  sendOrder: 'Enviar pedido',
  noNewProductsToSend:
    'Este pedido ya está enviado. Añade productos nuevos antes de volver a enviarlo.',
  lock: 'Bloquear',
  reset: 'Rehacer',
  prioritizeDispatch: 'Priorizar despacho',
  cancelOrder: 'Anular pedido',
  reprint: 'Reimprimir',
  mergeTablePrefix: 'se unirá a la mesa que seleccione',
  occupiedTablesOnly: 'solo se muestran mesas ocupadas',
  selectFreeTableForOrder:
    'Seleccione una mesa libre para trasladar el pedido',
  selectDestinationTable: 'Seleccione la mesa destino para',
  verifyBackend:
    'Verifica que el backend esté activo y vuelve a intentarlo.',
  newOrder: 'Nuevo pedido',
  processOrder: 'Procesar pedido',
  moveToTable: 'Trasladar a mesa',
  changeSpace: 'Cambiar espacio',
  mergeAccount: 'Unir cuenta',
  splitAccount: 'Dividir cuenta',
  activateSpace: 'Activar espacio',
  searchProducts: 'Buscar productos',
  selectSpace: 'Debe seleccionar un espacio.',
  mergeSpace: 'Unir espacio',
  changeSpaceTitle: 'Cambiar espacio',
  customerNamePlaceholder: 'Ingrese el nombre del cliente',
  courtesyCodeEntered: 'Código de cortesía ingresado',
  enteredCode: 'El código ingresado es: {{code}}',
  deleteCode: 'Eliminar código',
  keepCode: 'Mantener código',
  codeDeleted: 'Código eliminado',
  enterCourtesyCode: 'Ingresar código de cortesía',
  enterHostessCodes: 'Ingresar códigos de anfitrionas',
  codeLabel: 'Código {{number}}',
  addMore: 'Agregar más',
  enterHostessCode: 'Ingresar código de anfitriona {{number}}',
  orderNotFound: 'No existe el pedido.',
  productTransfer: 'Traslado de producto',
  selectTable: 'Debe seleccionar una mesa.',
  transferToTable: 'Trasladar a mesa',
  selectOrder: 'Debe seleccionar un pedido.',
  couldNotMoveOrder: 'No se pudo trasladar el pedido.',
  errorMovingOrder: 'Ocurrió un error al trasladar el pedido.',
  couldNotTransferProduct: 'No se pudo realizar el traslado.',
  errorMovingProduct: 'Ocurrió un error al trasladar el producto.',
  enterGuestCount: 'Ingrese N.º de personas',
  positiveNumberRequired: 'Ingrese un número válido mayor que cero.',
  orderNotFoundInSpace: 'No existe el pedido en este espacio.',
  unexpectedError: 'Algo salió mal',
  addQuantityFirst: 'Agregue primero la cantidad.',
  confirmDeleteProduct: '¿Está seguro de eliminar {{product}}?',
  enterAdministratorCode: 'Ingresar código de administrador',
  invalidCode: 'Código inválido',
  incorrectCode: 'El código ingresado no es correcto.',
  enterPrice: 'Ingresar precio',
  confirmVoidSpaceOrder:
    '¿Está seguro de anular el pedido de {{space}}?',
  processOrderTitle: 'Procesar pedido',
  confirmRemoveDiscount: '¿Está seguro de quitar el descuento?',
  yes: 'Sí',
  no: 'No',
  orderNotFoundInAccount: 'No existe el pedido en la cuenta.',
  printPreBill: 'Imprimir precuenta',
  noProductsEntered: 'Añade al menos un producto antes de enviar el pedido.',
  allProductsMustBeSaved:
    'No se guardaron todos los productos de la lista.',
  orderMustBeSaved: 'Envíe primero el pedido antes de emitir el comprobante.',
  savedOrderRequiredForOperation:
    'Envíe primero el pedido antes de realizar esta operación.',
  internalErrorRefresh: 'Error interno. Actualice la pantalla.',

  closeShift: 'Cerrar turno',
  closingShift: 'Cerrando turno…',
  shiftNumber: 'N.º de turno',
  startDate: 'Fecha de inicio',
  currentDate: 'Fecha actual',
  exchangeRate: 'Tipo de cambio',
  status: 'Estado',
  shiftClosed: 'TURNO CERRADO',
  selectOpenShiftRegister:
    'Selecciona una caja con un turno abierto para cerrarlo.',
  partialClose: 'Cierre parcial',
  partialCloseHint:
    'Omite la validación de pedidos pendientes de cobrar.',
  pendingOrdersTitle: 'Pedidos pendientes de cobrar ({{count}})',
  pendingOrdersExplanation:
    'Estos pedidos impiden cerrar el turno. Puedes anularlos aquí o salir para cobrarlos desde Ventas. Después vuelve a intentar el cierre.',
  account: 'Cuenta',
  spaceOrChannel: 'Espacio / canal',
  void: 'Anular',
  revalidateClose: 'Revalidar cierre',
  openShift: 'Aperturar turno',
  shiftOpened: 'Turno {{number}} abierto',
  registerAlreadyOperational:
    'La caja seleccionada ya está operativa. No es necesario volver a aperturarla.',
  selectRegister: 'Seleccione una caja.',
  enterExchangeRate: 'Ingrese el tipo de cambio.',
  enterPositiveValue: 'Ingrese un valor mayor que cero.',
  workDate: 'Fecha de trabajo',
  openAction: 'Aperturar',
  noOpenShiftForRegister: 'No hay un turno abierto para esta caja.',
  couldNotCloseShift: 'No se pudo cerrar el turno.',
  shiftCloseTitle: 'Cierre de turno',
  shiftClosedSuccessfully: 'El turno se cerró correctamente.',
  voidOrderTitle: 'Anular pedido N.º {{number}}',
  voidOrderWarning:
    'Esta operación anulará el pedido completo y no puede deshacerse.',
  voidReason: 'Motivo de la anulación',
  enterVoidReason: 'Ingrese el motivo...',
  voidOrder: 'Anular pedido',
  voidReasonRequired: 'Debe ingresar el motivo de la anulación.',
  couldNotVoidOrder: 'No se pudo anular el pedido.',
  orderVoided: 'Pedido anulado',
  orderVoidedSuccessfully: 'El pedido se anuló correctamente.',
  unpaidSalesTitle: 'Ventas sin pago registrado',
  unpaidSalesQuestion:
    'Existen ventas sin pago registrado. ¿Son ventas al crédito?',
  document: 'Documento',
  confirmCreditSales: 'Sí, son al crédito',
  shiftOpenedTitle: 'Turno aperturado',
  registerAvailableForOperations:
    'La caja ya está disponible para registrar operaciones.',

  newDelivery: 'Nuevo delivery',
  newDeliveryOrderTab: 'Nuevo pedido',
  deliveryOperationsTab: 'Despachos y cobros',
  deliveryOperationsTitle: 'Motorizados y entregas',
  deliveryOperationsHint:
    'Asigna los pedidos al reparto propio y registra el pago cuando el motorizado regrese.',
  pendingOwnDeliveries: '{{count}} entregas pendientes',
  pendingDeliveryOrders: 'Pedidos de reparto propio',
  pendingDeliveryOrdersHint:
    'El pedido queda completado únicamente después de registrar el cobro.',
  loadingPendingDeliveries: 'Consultando entregas pendientes…',
  noPendingDeliveries: 'No hay entregas pendientes',
  noPendingDeliveriesHint:
    'Los pedidos cobrados desaparecen automáticamente de esta bandeja.',
  noAddress: 'Sin dirección registrada',
  ownDriver: 'Motorizado propio',
  noDriversAvailable: 'No hay empleados disponibles para reparto.',
  assigningDriver: 'Asignando…',
  assignDriver: 'Asignar motorizado',
  assignedDriver: 'Motorizado asignado',
  deliveryPaymentAlreadyRegistered: 'Pago ya registrado',
  confirmDeliveryAndCharge: 'Confirmar entrega y registrar pago',
  chooseDeliveryOrigin:
    'Elige cómo se recibió el pedido antes de identificar al cliente.',
  businessPartnersCount: '{{count}} socios de negocio',
  deliveryMode: 'Modalidad de delivery',
  phoneDelivery: 'Delivery por teléfono',
  phoneDeliveryHint:
    'Busca o registra el teléfono y la dirección del cliente.',
  businessPartnerOrder: 'Pedido de un socio de negocio',
  businessPartnerExamples:
    'Glovo, Uber Eats u otra plataforma con precios propios.',
  noBusinessPartners: 'No hay socios de negocio configurados.',
  selectDeliveryMode: 'Selecciona una modalidad para continuar',
  selectDeliveryModeHint:
    'Así el pedido conservará correctamente su origen y sus reglas de precio.',
  externalOrderData: 'Datos del pedido externo',
  noPhoneRecordForExternalOrder:
    'No se crea una ficha telefónica para este pedido',
  businessPartner: 'Socio de negocio',
  selectOriginBusinessPartner:
    'Selecciona el socio de negocio que originó el pedido.',
  customerName: 'Nombre del cliente',
  customerNameRequired: 'El nombre del cliente es obligatorio.',
  unnamedCustomer: 'Sin nombre',
  businessPartnerPricesHint:
    'Al continuar se aplicarán los precios configurados para el socio. Si un producto no tiene precio especial, conservará su precio normal.',
  deliverySearchLabel: 'Teléfono, cliente, documento o dirección',
  clearSearch: 'Limpiar búsqueda',
  newDestination: 'Nuevo destino',
  destinationsFound: 'Destinos encontrados',
  destinations: 'Destinos',
  foundCount: '{{count}} encontrados',
  loadingCustomers: 'Consultando clientes…',
  noDestinationFound: 'No encontramos un destino',
  registerWithoutLeavingSale:
    'Puedes registrarlo sin abandonar la venta.',
  registerDestination: 'Registrar destino',
  selectDestination: 'Selecciona un destino',
  createDestinationHint:
    'También puedes crear uno nuevo para continuar con el pedido.',
  deliveryData: 'Datos de entrega',
  newCustomerAddress: 'Nueva dirección del cliente',
  newDestinationTitle: 'Nuevo destino',
  customerAddressReference:
    'Cliente {{customer}} · Dirección {{address}}',
  customerReference: 'Cliente {{customer}} · {{name}}',
  addAnotherAddress: 'Agregar otra dirección a este cliente',
  phoneValidation: 'Ingresa un teléfono de 7 a 15 dígitos.',
  shortInstruction: 'Anexo / indicación corta',
  recipientName: 'Nombre de quien recibe',
  nameRequired: 'El nombre es obligatorio.',
  deliveryAddress: 'Dirección de entrega',
  addressRequired: 'La dirección es obligatoria.',
  reference: 'Referencia',
  deliveryPrice: 'Precio del delivery',
  deliveryProductAdded: 'Se agregará {{product}} al pedido.',
  configureDeliveryProduct:
    'Configura primero el producto de cargo por delivery.',
  priceCannotBeNegative: 'El precio no puede ser negativo.',
  identityType: 'Tipo de identidad',
  identityNumber: 'Número de identidad',
  businessNameOrCustomer: 'Razón social / nombre del cliente',
  fieldRequired: 'Este campo es obligatorio.',
  email: 'Correo',
  validEmailRequired: 'Ingresa un correo válido.',
  recentOrders: 'Últimos pedidos',
  deliverySalesHistory: 'Historial de ventas delivery del cliente',
  loadingHistory: 'Consultando historial…',
  noDeliverySales:
    'Aún no hay ventas delivery asociadas a este cliente.',
  productsCount: '{{count}} productos',
  continueToOrder: 'Continuar al pedido',
  continue: 'Continuar',
  checkingPrices: 'Consultando precios…',
  generalSales: 'Listado de ventas generales',
  allShiftsAndRegisters: 'Todos los turnos y cajas',
  includeExpressSales: 'Incluir ventas express',
  searchBy: 'Buscar por',
  documentType: 'Tipo de documento',
  documentNumber: 'N.º doc.',
  currency: 'Moneda',
  state: 'Estado',
  options: 'Opciones',
  saleFound: '{{count}} venta encontrada',
  salesFound: '{{count}} ventas encontradas',
  fromTotal: 'de {{count}}',
  update: 'Actualizar',
  newSale: 'Nueva venta',
  issueCreditNote: 'Emitir nota de crédito',
  pendingUseCase: 'Caso de uso pendiente de implementar',
  saleActions: 'Acciones de la venta',
  noSalesFound:
    'No se encontraron ventas con los criterios seleccionados.',
  modifyDocument: 'Modificar documento',
  modifyPayments: 'Modificación de pagos',
  getPdfAndXml: 'Obtener PDF y XML',
  reprintDocument: 'Reimprimir documento',
  salesPagination: 'Paginación de ventas',
  selectDocument: 'Seleccione un documento.',
  selectSaleToVoid: 'Debe seleccionar una venta para anular.',
  confirmVoidDocument:
    '¿Está seguro de anular el documento {{document}}?',
  actionCannotBeUndone: 'Esta acción no se puede deshacer.',
  yesVoid: 'Sí, anular',
  noCancel: 'No, cancelar',
  voided: 'Anulado',
  documentVoidedSuccessfully: 'El documento se anuló con éxito.',
  couldNotVoidDocument: 'No se pudo anular el documento.',
  paymentAndIssueDocument: 'Pago y emisión de comprobante',
  documentData: 'Datos del comprobante',
  series: 'Serie',
  number: 'Número',
  customerData: 'Datos del cliente',
  removeCustomerData: 'Quitar datos del cliente',
  customerDocumentType: 'Tipo de documento del cliente',
  requiredField: 'El campo es requerido.',
  invalidExpectedFormat: 'Formato inválido{{expected}}.',
  expectedFormat: ' — esperado: {{mask}}',
  invalidNumberForAmount: 'Número inválido para el monto actual.',
  miscellaneousCustomerRule:
    'La razón social debe ser "Cliente Varios" cuando el documento es 00000001.',
  address: 'Dirección',
  invalidEmailFormat: 'El formato del correo es incorrecto.',
  addCustomerData: 'Añadir datos del cliente',
  totalToPay: 'Total a pagar',
  paidReference: 'de {{symbol}} {{total}} · pagado {{symbol}} {{paid}}',
  cashPayments: 'Pagos en efectivo',
  exact: 'EXACTO',
  automaticCharge: 'Auto-cobra',
  exactCashHint:
    'Cobra {{symbol}} {{amount}} exacto en efectivo y cierra automáticamente',
  currencyFallback: 'Moneda',
  enter: 'Ingresar',
  entered: 'Ingresado',
  exchangeRateLabel: 'Tipo de cambio:',
  cardPayments: 'Pagos con tarjeta',
  card: 'Tarjeta',
  authorization: 'Autorización',
  paidAmount: 'Monto',
  tip: 'Propina',
  actions: 'Acciones',
  add: 'Agregar',
  noCardPayments: 'Sin pagos con tarjeta registrados',
  charge: 'Cobrar',
  remaining: 'Falta',
  changeDue: 'Vuelto',
  paymentExcess: 'Exceso',
  calculatedTotalMismatch:
    'El monto calculado no coincide con el que muestra la pantalla de caja. Vuelva a intentarlo.',
  totalTimeout:
    'No se pudo obtener el total a pagar. Se agotó el tiempo de espera.',
  system: 'Sistema',
  registerInfoNotFound: 'No se encontró información de la caja.',
  selectedDocumentTypeNotFound:
    'No se encontró el tipo de documento seleccionado.',
  getRegisterError: 'Error al obtener la caja.',
  cardAmountExceedsTotal:
    'El monto de tarjeta sobrepasa el monto a pagar.',
  enterCardPaymentAmount: 'Ingrese el monto pagado con tarjeta.',
  mainCurrency: 'Moneda principal',
  selectCustomerIdentityType:
    'Seleccione el tipo de documento del cliente.',
  enterCustomerIdentityNumber:
    'Ingrese el número de identificación del cliente.',
  enterCustomerBusinessName:
    'Ingrese el nombre o razón social del cliente.',
  enterValidCustomerIdentity:
    'Ingrese correctamente el número de identificación del cliente.',
  enterCustomerAddress: 'Ingrese la dirección del cliente.',
  genericIdentityNameRule:
    'Si el número de identidad es 00000001, el nombre del cliente debe ser "Cliente Varios".',
  genericCustomerIdentityRule:
    'Si el cliente es "Cliente Varios", el número de identidad debe ser 00000001.',
  amountRequiresCustomerIdentity:
    'Para este importe debe ingresar el documento de identidad del cliente.',
  invalidCustomerEmail: 'El correo electrónico está mal ingresado.',
  confirmChargeAccount: '¿Está seguro de cobrar la cuenta?',
  confirmCreditSale: '¿Está seguro de registrar la venta al crédito?',
  message: 'Mensaje',
  paymentBelowTotal:
    'El total de pago es menor que el monto a pagar.',
  preferredFormat: '¿Qué formato prefiere?',
  chooseOption: 'Elija una opción',
  ticket: 'Ticket',
  customerNotFound: 'No se encontró el cliente.',
  retrySearchTimeout:
    'Vuelva a realizar la búsqueda. Se agotó el tiempo de espera.',
  amountCalculationError: 'Ocurrió un error al calcular los montos.',
  description: 'Descripción',
  descriptionRequired: 'La descripción es requerida.',
  required: 'Requerido.',
  updateAction: 'Actualizar',
  edit: 'Editar',
  active: 'Activo',
  inactive: 'Inactivo',
  family: 'Familia',
  familyRequired: 'La familia es requerida.',
  searchByDescription: 'Buscar por descripción',
  descriptionOrStatus: 'Descripción, estado...',
  maintenanceFamilies: 'Mantenimiento de familias',
  newFamily: 'Nueva familia',
  maintenanceSubfamilies: 'Mantenimiento de subfamilias',
  newSubfamily: 'Nueva subfamilia',
  productGroups: 'Grupos de productos',
  newGroup: 'Nuevo grupo',
  maintenancePrintAreas: 'Mantenimiento de áreas de impresión',
  newPrintArea: 'Nueva área',
  descriptionOrPrinter: 'Descripción o impresora...',
  printerName: 'Nombre real de la impresora',
  printerExample: 'Ej. EPSON_TM20, HP_LaserJet...',
  printersOnThisDevice: 'Impresoras de este equipo',
  printersOnThisDeviceHelp: 'Comprueba que cada nombre real configurado exista exactamente igual en QZ/Windows en este ordenador.',
  printerOnThisDevice: 'Impresora en este equipo',
  selectPrinter: 'Seleccionar impresora',
  doNotPrintOnThisDevice: 'No imprimir en este equipo',
  defaultPrinter: 'Predeterminada',
  validationStatus: 'Validación',
  qzConnected: 'QZ conectado',
  qzUnavailable: 'QZ no disponible',
  checkingQz: 'Comprobando QZ',
  checkThisDevice: 'Validar este equipo',
  saveDevicePrinters: 'Guardar impresoras',
  testPrint: 'Probar',
  printerNotConfiguredOnDevice: 'Sin configurar en este equipo',
  printerNotFoundOnDevice: 'No encontrada en este equipo',
  printerReadyToSave: 'Encontrada · pendiente de validar',
  printerValidatedOnDevice: 'Validada en este equipo',
  maintenanceColors: 'Mantenimiento de colores',
  newColor: 'Nuevo color',
  descriptionOrRgb: 'Descripción o RGB',
  color: 'Color',
  chooseColor: 'Elegir color',
  maintenanceStations: 'Mantenimiento de estaciones',
  newStation: 'Nueva estación',
  searchStation: 'Buscar por nombre o identificador único',
  uniqueIdentifier: 'Identificador único',
  type: 'Tipo',
  stationType: 'Tipo de estación',
  assignedRegister: 'Caja asignada',
  maintenanceEnvironments: 'Mantenimiento de ambientes',
  newEnvironment: 'Nuevo ambiente',
  searchEnvironment: 'Buscar por descripción, estado o posición',
  position: 'Posición',
  selectState: 'Seleccione un estado.',
  selectPosition: 'Seleccione una posición (1 a 10)',
  choosePosition: 'Elegir posición (1 × 10)',
  maintenanceObservations: 'Mantenimiento de observaciones',
  newObservation: 'Nueva observación',
  descriptionTypePosition: 'Descripción, tipo, posición...',
  observationExample: 'Ej. BIEN CALIENTE, SALSA APARTE, ...',
  selectGridPosition:
    'Seleccione la posición ({{rows}} x {{cols}}) — Tipo: {{type}}',
  selected: 'Seleccionada',
  occupied: 'Ocupada',
  free: 'Libre',
  maintenanceEmployees: 'Mantenimiento de empleados',
  newEmployee: 'Nuevo empleado',
  searchEmployee: 'Buscar por nombre, documento de identidad, etc.',
  name: 'Nombre',
  identityDocument: 'Documento de identidad',
  identityRequired: 'El documento de identidad es requerido.',
  nameRequiredField: 'El nombre es requerido.',
  addressRequiredField: 'La dirección es requerida.',
  telephone: 'Teléfono',
  validPhoneRequired: 'Introduzca un teléfono válido.',

  // Mantenimiento de cajas
  maintenanceRegisters: 'Mantenimiento de cajas',
  newRegister: 'Nueva caja',
  searchRegister: 'Descripción, default...',
  defaultRegister: 'Caja por defecto',
  salesChannel: 'Canal de venta',
  enabledSalesChannels: 'Canales de venta habilitados',
  defaultSalesChannel: 'Canal de venta por defecto',
  selectAtLeastOneChannel: 'Selecciona al menos un canal arriba.',
  emitsPreBill: 'Emite precuenta',
  emitsKitchenTicket: 'Emite comanda',
  emitsDiscount: 'Emite descuento',
  allowsSplitOrder: 'Permite dividir pedido',
  allowsPartialClose: 'Permite cierre parcial',
  onlineElectronicSubmission: 'Envío electrónico online',
  automaticDeliveryPreBill: 'Precuenta delivery automática',
  allowTaxiPayments: 'Permitir pago a taxistas',

  // Mantenimiento de descuentos
  maintenanceDiscounts: 'Mantenimiento de descuentos',
  newDiscount: 'Nuevo descuento',
  searchDiscount: 'Descripción, tipo...',
  percentage: 'Porcentaje',
  clickToActivate: 'Clic para activar',
  clickToDeactivate: 'Clic para desactivar',
  noDiscountsRegistered: 'Sin descuentos registrados.',
  editDiscount: 'Editar descuento',
  discountType: 'Tipo de descuento',
  selectType: 'Seleccione un tipo.',
  enterPercentageGreaterThanZero: 'Ingresa un porcentaje mayor a 0.',
  valeTypeNoPercentage: 'El tipo Vale no requiere porcentaje.',

  // Mantenimiento de clientes
  maintenanceCustomers: 'Mantenimiento de clientes',
  newCustomer: 'Nuevo cliente',
  searchCustomer: 'Buscar por nombre, RUC, etc.',
  businessName: 'Razón social',
  businessNameRequired: 'La razón social es requerida.',

  // Mantenimiento de productos
  maintenanceProducts: 'Mantenimiento de productos',
  newProduct: 'Nuevo producto',
  searchProduct: 'Nombre, descripción, precio, posición...',
  shortName: 'Nombre corto',
  visible: 'Visible',
  productTypeMenuCard: 'Carta',
  productTypeMenu: 'Menú',
  productTypeWithComplements: 'Con complementos',
  productTypeComplement: 'Complemento',
  subfamily: 'Subfamilia',
  group: 'Grupo',
  menuSection: 'Sección de menú',
  requiredForMenu: 'Requerido para Menú.',
  complementsQuantity: 'Cantidad de complementos',
  requiredForType2: 'Requerido para Tipo=2.',
  complementFactor: 'Factor complemento',
  complementFactorHint: '> 0 (2 decimales).',
  complementPosition: 'Posición complemento',
  selectPosition6x5: 'Seleccione posición 6×5',
  choosePosition6x5: 'Elegir posición (6×5)',
  selectPosition8x9: 'Seleccione posición 8×9',
  choosePosition8x9: 'Elegir posición (8×9)',
  minimumPrice: 'Precio mínimo',
  requiredIfNoPrice: 'Requerido si "Sin precio".',
  idAndClassification: 'Identificación y clasificación',
  configAndPrintAreas: 'Configuración y áreas de impresión',
  advancedConfiguration: 'Configuración avanzada',
  advancedConfigurationHint: 'Abra esta sección solo cuando el producto necesite un comportamiento especial.',
  showAdvancedConfiguration: 'Configurar',
  hideAdvancedConfiguration: 'Ocultar configuración',
  directStockControl: 'Control directo de stock',
  directStockControlHint: 'Descuenta el stock propio de este producto al venderlo.',
  tax: 'Impuesto',
  noPrice: 'Sin precio',
  exclusiveHostess: 'Exclusivo anfitriona',
  allowsCourtesyDrink: 'Permite trago cortesía',
  printAreas: 'Áreas de impresión',
  printAreasHint: 'Selecciona una o varias áreas donde se imprimirá la comanda de este producto.',
  invalidPrice: 'Precio inválido.',

  // Mantenimiento de socios de negocio
  maintenanceBusinessPartners: 'Mantenimiento de socios de negocio',
  newBusinessPartner: 'Nuevo socio',
  searchBusinessPartner: 'Buscar socio',
  commission: 'Comisión',
  configuredPrices: 'Precios configurados',
  editPartnerAndPrices: 'Editar socio y precios',
  deleteBusinessPartner: 'Eliminar socio',
  loadingBusinessPartners: 'Cargando socios…',
  businessPartnerName: 'Nombre del socio de negocio',
  businessPartnerNameRequired: 'El nombre del socio es obligatorio.',
  mustBeBetween0And100: 'Debe estar entre 0 y 100.',
  partnerActiveForDelivery: 'Socio activo para delivery',
  specialProductPrices: 'Precios especiales por producto',
  normalPrice: 'Precio normal',
  partnerPrice: 'Precio del socio',
  useNormalPrice: 'Usar precio normal',
  noProductsMatchSearch: 'No hay productos que coincidan con la búsqueda.',
  saveBusinessPartner: 'Guardar socio',
  backToList: 'Volver al listado',

  // Mantenimiento de espacios
  maintenanceSpaces: 'Mantenimiento de espacios',
  newSpace: 'Nuevo espacio',
  searchSpace: 'Buscar por tipo, número, posición o ambiente',
  spaceType: 'Tipo de espacio',
  environment: 'Ambiente',
  selectEnvironment: 'Seleccione un ambiente.',
  numberRequiredGreaterThanZero: 'El número es requerido y debe ser mayor a 0.',
  selectPositionSimple: 'Seleccione una posición',
  choosePositionSimple: 'Elegir posición',
  selectIfActive: 'Seleccione si está activo.',
  selectIfVisible: 'Seleccione si es visible.',

  // Mantenimiento de usuarios
  maintenanceUsers: 'Mantenimiento de usuarios',
  newUser: 'Nuevo usuario',
  searchUser: 'Buscar por nombre de usuario, nivel de usuario, etc.',
  username: 'Nombre de usuario',
  level: 'Nivel',
  usernameRequired: 'El nombre de usuario es requerido.',
  passwordRequired: 'La contraseña es requerida.',
  employee: 'Empleado',
  selectValidEmployee: 'Seleccione un empleado válido.',
  selectRole: 'Seleccione un cargo.',
  changePassword: 'Cambiar contraseña',
  cancelChange: 'Cancelar cambio',
  currentPassword: 'Contraseña actual',
  newPassword: 'Nueva contraseña',
  confirmPassword: 'Confirmar contraseña',
  passwordsDoNotMatch: 'Las contraseñas no coinciden',
  savePassword: 'Guardar contraseña',

  // Diálogos pequeños (mcant, mtext, delete-product, mozo)
  switchToNumeric: 'Cambiar a numérico',
  switchToLetters: 'Cambiar a letras',
  clear: 'Borrar',
  confirmVoidTitle: 'Confirmar anulación',
  administrator: 'Administrador',
  authenticate: 'Autenticar',
  tableData: 'Datos de mesa',
  tableNumber: 'N.° de mesa',
  guests: 'N.° de personas',
  onlyNumbers: 'Solo números',
  observations: 'Observaciones',
  writeManualObservation: 'Escribir observación manual',
  food: 'Comidas',
  drinks: 'Bebidas',
  selectPositionTitle: 'Seleccionar posición',

  // Diálogos de entradas / taxista (entradas, pagar-taxista)
  admissionQuery: 'Consulta de Entradas',
  taxiDriverData: 'Datos del taxista',
  idDocument: 'DNI',
  givenNames: 'Nombres',
  licensePlate: 'Placa',
  admissionsCourtesyDrinks: 'Entradas · tragos de cortesía',
  searchByCode: 'Buscar por código',
  selectAdmissionHint: 'Selecciona una entrada de la lista para calcular el Total a Pagar.',
  docTypeShort: 'Tipo Doc',
  promoCode: 'Código Promo',
  registrationDate: 'Fecha Reg',
  noResultsForCode: 'Sin resultados para ese código.',
  noAdmissionsRegistered: 'No hay entradas registradas.',
  payTaxiDriver: 'Pagar Taxista',
  admissionSales: 'Ventas de Entradas',
  memberAdmission: 'Entrada de Socios',
  guestAdmission: 'Entrada de Invitados',
  processFreeAdmission: 'Procesar Entrada Gratis',
  consumptionAdmission: 'Entrada por Consumo',
  processConsumptionAdmission: 'Procesar Entrada xConsumo',
  nationalAdmission: 'Entrada Nacional',
  internationalAdmission: 'Entrada Internacional',
  admissionsLower: 'entradas',
  newPrice: 'Nuevo precio',
  freeDrinks: 'Tragos Gratis',
  courtesyDrinksLower: 'tragos de cortesía',
  subtract: 'Restar',
  cameWithTaxiDriver: 'Vino con taxista',
  addNationalAdmission: 'Sumar entrada nacional',
  addInternationalAdmission: 'Sumar entrada internacional',
  salesReceipt: 'Boleta',
  invoice: 'Factura',

  // Diálogo de informe contable (reportecontable)
  reportType: 'Tipo de informe',
  accountingReport: 'Informe Contable',
  sales: 'Ventas',
  purchases: 'Compras',
  initialDate: 'Fecha inicial',
  finalDate: 'Fecha final',
  endDateBeforeStart: 'La fecha final no puede ser anterior a la inicial.',
  allMasculine: 'Todos',
  allFeminine: 'Todas',
  exporting: 'Exportando…',
  exportToExcel: 'Exportar a Excel',
  colorRed: 'ROJO',
  colorBlue: 'AZUL',
  colorWhite: 'BLANCO',
  colorBlack: 'NEGRO',
  colorYellow: 'AMARILLO',

  // Diálogos de búsqueda de producto / complementos / resumen de pedido
  searchByProduct: 'Buscar por producto',
  typeToFilter: 'Escribe para filtrar…',
  complements: 'Complementos',
  selectComplement: 'Seleccionar complemento',
  addOnsQty: 'Cant. Complem.',
  factorShort: 'Ft',
  increase: 'Aumentar',
  limit: 'Límite',
  orderSummary: 'RESUMEN PEDIDO',
  moreProducts: 'Mas productos',

  // Diálogos de descuento / división de cuenta
  discountBySale: 'Descuento por Venta',
  byProduct: 'Por Producto',
  voucher: 'Vale',
  searchDiscountLabel: 'Buscar descuento',
  descriptionEllipsis: 'Descripción...',
  noDiscountsForType: 'Sin descuentos para este tipo.',
  newAccount: 'Nueva Cuenta',
  showOrder: 'Mostrar Pedido',
  space: 'Espacio',
  accounts: 'Cuentas',
  accountNumber: 'Nº Cuenta',
  products: 'Productos',
  quantityFull: 'Cantidad',
  tapProductToMove: 'Toca un producto para moverlo →',
  tapProductToReturn: 'Toca un producto para devolverlo ←',
  confirm: 'Confirmar',

  // Lógica del diálogo de descuento (dialog-descuento .ts)
  amountLabel: 'Monto',
  numberLabel: 'Numero',
  reservationNumber: 'N° Reserva',
  enterDiscountForSale: 'Ingrese un descuento para la venta',
  maxVoucherDiscount: 'El descuento por Vale máximo debe ser {{max}}.',
  enterCouponVoucherReservation: 'Ingrese el número del Cupón, Vale o Reserva',
  enterVoucherValue: 'Ingrese el Valor del Vale',
  confirmExecuteDiscount: '¿Está seguro de ejecutar el descuento?',

  // Diálogos de venta rápida / documentos emitidos
  quickSaleRecord: 'Registro de Venta Rápida',
  documentDate: 'Fecha Documento',
  currencySoles: 'SOLES',
  currencyDollars: 'DÓLARES',
  shiftDate: 'Fecha Turno',
  sell: 'Venta',
  buy: 'Compra',
  onlyNumericValues: 'Debe ingresar solo valores numéricos.',
  grandTotal: 'Gran Total',
  salesDocuments: 'Documentos de Ventas',
  onCredit: 'Al Crédito',
  mixed: 'Mixto',
  doiNumber: 'N° DOI',
  paymentMethodShort: 'F. Pago',
  pdfAndXml: 'PDF y XML',
  voidReasonPlaceholder: 'Motivo de anulación (requerido para anular)',
  virtualKeyboard: 'Teclado virtual',
  correctIssuedSale: 'Corregir venta emitida',
  correctIssuedSaleHint: 'Seleccione qué necesita corregir',
  correctionKeepsAuditTrail:
    'El documento original nunca se sobrescribe. Antes de aplicar cambios, el sistema mostrará el tratamiento fiscal correspondiente.',
  loadingDocumentCorrection: 'Cargando los datos del documento...',
  correctionPayments: 'Formas de pago',
  correctionPaymentsHint: 'Cambie efectivo, tarjeta o pago mixto sin alterar la condición fiscal de la venta.',
  correctionCustomer: 'Datos del cliente',
  correctionCustomerHint: 'Corrija identificación, razón social, dirección o correo impresos.',
  correctionDocumentType: 'Tipo de documento',
  correctionDocumentTypeHint: 'Sustituya la boleta, factura o factura simplificada por el tipo solicitado.',
  cash: 'Efectivo',
  courtesy: 'Cortesía',
  cheque: 'Cheque',
  deposit: 'Depósito',
  addPaymentMethod: 'Agregar forma de pago',
  paymentNetTotal: 'Total neto pagado',
  targetDocumentType: 'Nuevo tipo de documento',
  documentGivenToCustomer: 'El documento original fue entregado al cliente',
  documentGivenToCustomerHint:
    'Para SUNAT, este dato determina si corresponde comunicar una baja o emitir una nota de crédito.',
  correctionReasonPlaceholder: 'Explique por qué se requiere esta corrección',
  correctionReasonRequired: 'Ingrese un motivo de al menos 3 caracteres.',
  confirmPaymentChange: 'Confirmar cambio de pago',
  confirmPaymentChangeHint: 'Se guardarán las nuevas formas de pago. ¿Desea continuar?',
  applyPaymentChange: 'Aplicar cambio',
  confirmCustomerCorrection: 'Confirmar corrección del cliente',
  confirmCustomerCorrectionHint: 'Se emitirá un nuevo comprobante con los datos corregidos. ¿Desea continuar?',
  confirmDocumentChange: 'Confirmar cambio de documento',
  confirmDocumentChangeHint: 'Se emitirá un nuevo comprobante del tipo seleccionado. ¿Desea continuar?',
  applyCorrection: 'Aplicar corrección',
  reviewCorrection: 'Revisar corrección',
  correctionConfirm: 'Confirmar y aplicar',
  correctionApplied: 'Corrección registrada',
  correctionCompleteRequiredFields:
    'Complete los datos obligatorios y verifique que el pago neto coincida con el total de la venta.',
  correctionCustomerRequiredFields:
    'Complete los datos obligatorios del cliente y del documento.',
  correctionIdentityTypeRequired:
    'Seleccione el tipo de identificación del cliente.',
  correctionIdentityTypeNotValidForInvoice:
    'Seleccione un tipo de identificación permitido para facturas.',
  correctionIdentityNumberRequired:
    'Ingrese el número de identificación del cliente.',
  correctionIdentityNumberInvalid:
    'El número no tiene un formato válido de {{type}}.',

  // Lógica del diálogo de documentos emitidos (dialog-documentos-emitidos .ts)
  ok: 'OK',
  enterVoidReasonMsg: 'Ingrese el Motivo de Anulación',
  noPermissionEnterAdminKey:
    'No tiene permiso. Ingresa la Clave del Administrador',
  confirmVoidThisDocument: '¿Está seguro de Anular el Documento?',
  voidOrderTitleSimple: 'Anular Pedido',
  alsoVoidOrder: '¿Anular también el Pedido?',
  administratorCode: 'Código de Administrador',
  operationCancelled: 'Operación cancelada',
  attention: 'Atención',

  // Lógica del diálogo de venta rápida (dialog-emitir-venta .ts)
  mustOpenShiftToIssue:
    'Debe aperturar un turno de la {{register}} para poder emitir un comprobante de venta.',
  cannotAddQtyCombo:
    'No se puede agregar una Cantidad desde esta opcion para un Producto Combo.',
  cannotAddQtyComplements:
    'No se puede agregar una Cantidad desde esta opcion para un Producto que tiene Complementos.',
  productInSolesNeedBuyRate:
    'El producto {{product}} está en SOLES. Para realizar la venta en DOLARES es necesario ingresar el Tipo de Cambio COMPRA.',
  productInDollarsNeedSellRate:
    'El producto {{product}} está en DOLARES. Para realizar la venta en SOLES es necesario ingresar el Tipo de Cambio VENTA.',
  productNoStockContinue:
    'El producto no tiene Stock. ¿Desea continuar de todas formas?',
  noSaleProductEntered: 'No ha ingresado ningún producto de venta.',

  // Reportes del dashboard
  reportsDashboard: 'Dashboard de reportes',
  dashboardSubtitle:
    'Analiza ventas, popularidad de platos y rendimiento por rango de fechas.',
  dashboardFooter: '© 2024 LaComanda · Dashboard de Restaurantes.',
  noDataForRange: 'Sin datos para el rango seleccionado.',
  period: 'Periodo',
  daily: 'Diarias',
  weekly: 'Semanales',
  monthly: 'Mensuales',
  dailyWeeklyMonthly: 'Diarias · Semanales · Mensuales',
  dailySales: 'Ventas Diarias',
  loadingSales: 'Cargando ventas...',
  totalSale: 'Total venta',
  loadingChannels: 'Cargando canales...',
  salesByChannel: 'Ventas por canal',
  spaceTakeawayDelivery: 'Espacio · Llevar · Delivery',
  takeaway: 'Llevar',
  loadingPopularity: 'Cargando popularidad...',
  dishPopularity: 'Popularidad de platos',
  topBestSellingDishes: 'Top de platos más vendidos',
  top: 'Top',
  loadingPeakHours: 'Cargando horas pico...',
  peakHours: 'Horas pico',
  daySegments: 'Segmentos del día',
  timeSlot: 'Franja',
  afternoon: 'Tarde',
  night: 'Noche',
  lateNight: 'Madrugada',
  peakHour: 'Hora pico',
  transactions: 'Transacciones',
  totalTransactions: 'Total transacciones',
  loadingVoids: 'Cargando anulaciones...',
  voids: 'Anulaciones',
  byProductAndReason: 'Por producto y motivo',
  reason: 'Motivo',
  authorizedBy: 'Autoriza',

  // Diálogos de lista de pedidos / ver pedido / documentos por caja
  orderList: 'LISTA DE PEDIDOS',
  select: 'Seleccionar',
  orderTime: 'Hora Pedido',
  documentsByRegister: 'Documentos por Caja',
  loading: 'Cargando...',
  enableAll: 'Activar todos',
  disableAll: 'Desactivar todos',
  currentNumber: '# Actual',
  copies: 'Copias',
  itemsPerDoc: 'Items x Doc',
  askWhenPrinting: 'Preguntar al imprimir',
  mask: 'Mascara',

  // Diálogo de gastos y reportes (dialog-reportes)
  openPrint: 'Abrir / Imprimir',
  print: 'Imprimir',
  closeView: 'Cerrar vista',
  collectionsSummary: 'Resumen de Cobros',
  collected: 'Cobrado',
  pendingCollection: 'Por Cobrar',
  salesReports: 'Reportes de Ventas',
  adminsOnly: 'Solo administradores',
  viewPdf: 'Ver PDF',
  generating: 'Generando...',
  salesByProduct: 'Ventas por Producto',
  salesSummary: 'Resumen de Ventas',
  documentsSummary: 'Resumen de Documentos',
  onlyElectronicDocs: 'Solo Doc. Electrónicos',
  onlyExpress: 'Solo Express',
  expenses: 'Egresos',
  shiftExpenses: 'Egresos del Turno',
  expenseEntry: 'Registro de Egresos',
  detailedReport: 'Reporte Detallado',
  summaryReport: 'Reporte Resumido',
  tracking: 'Seguimiento',
  orderTracking: 'Seguimiento de Comandas',
  hostessCommission: 'Comisión Anfitriona',
  currentShift: 'Turno actual',
  dateRange: 'Rango de fechas',
  commands: 'Comandas',
  paid: 'Pagado',
  pending: 'Pendiente',
  orderType: 'Tipo de pedido',
  commandNumber: 'N.º comanda',
  table: 'Mesa',
  waiter: 'Mozo',
  registeredBy: 'Registrado por',
  voidedProducts: 'Productos anulados',
  voidedOrdersAmount: 'Comandas anuladas',
  voidedProductsAmount: 'Productos anulados',
  subtotal: 'Subtotal',
  voidedBy: 'Anulado por',
  voidedAt: 'Fecha de anulación',
  authorizedAt: 'Fecha de autorización',
  noDataForFilter: 'No se encontraron datos para el filtro seleccionado.',
  hostessCards: 'Fichas de anfitriona',
  assignedAmount: 'Importe asignado',
  hostesses: 'Anfitrionas',
  netAmount: 'Importe neto',
  amountPerHostess: 'Importe por anfitriona',
  reprints: 'Reimpresiones',
  incomeType: 'Tipo de ingreso',

  // Configurar este ordenador (configurar-ordenador)
  configureThisComputer: 'Configurar este ordenador',
  identifierPlaceholder: 'Ej. 9b5d-... o un alias propio',
  identifierHint: 'Solo letras, números, “-”, “_” o “.” — 6 a 64 caracteres',
  min6Chars: 'Mínimo 6 caracteres',
  max64Chars: 'Máximo 64 caracteres',
  invalidFormat: 'Formato no válido',
  generate: 'Generar',
  deleteIdentifier: 'Eliminar identificador',
  current: 'Actual',
  notConfigured: '(no configurado)',
  hostReference: 'Host (referencia)',
  identifierStorageNote:
    'Este identificador se guarda en este ordenador (cookie) y se usará al iniciar sesión para asociar esta estación en el sistema.',

  // Configuración inicial (configuracion-inicial)
  initialSetup: 'Configuración Inicial',
  configurationMaintenance: 'Configuración del restaurante',
  essentialBusinessData: 'Datos indispensables del negocio',
  initialSetupHint:
    'Completa solo estos datos para empezar. El país, la moneda, la identidad fiscal y los valores operativos se aplican automáticamente.',
  settingsAvailableLater:
    'Después podrás desactivar o ajustar cualquier opción incluida en tu licencia desde Configuración.',
  saveAndStart: 'Guardar y empezar',
  businessData: 'Datos de Negocio',
  countryIso2: 'País (ISO2)',
  defaultCurrency: 'Moneda por defecto',
  symbol: 'Símbolo',
  format: 'Formato',
  invalidFormatForCountryType: 'Formato inválido para el país / tipo seleccionado.',
  tradeName: 'Nombre Comercial',
  servicePercent: '% Servicio',
  min0Percent: 'Mínimo 0%',
  receiptFooter: 'Pie de Página (Comprobante)',
  operation: 'Operación',
  transfer: 'Traslado',
  allowPreBills: 'Permitir Precuentas',
  allowSpaceChange: 'Permitir Cambio de Espacio',
  dailyControl: 'Control Diario',
  preBillsNumber: 'N° de Precuentas',
  closingReports: 'Reportes en Cierre',
  settlement: 'Liquidación',
  itemConsumption: 'Consumo de Artículo',
  dailyExpenses: 'Gastos Diarios',
  includeExpressInClosing: 'Incluir "Express" en Cierre',
  includeExpressHint:
    'Si <strong>Incluir Express en Cierre</strong> está activo, los comprobantes internos (sin efecto fiscal) se incluirán en los reportes marcados arriba.',
  features: 'Características',
  enableHostessField: 'Habilitar campo "Anfitrionas" en Productos',
  hostessFieldHint:
    'Si está activo, en el mantenimiento de productos se mostrará y habilitará el campo <strong>ExclusivoParaAnfitriona</strong>.',
  internalProducts: 'Productos Internos',
  enablePosTips: 'Habilitar "propinas cobradas en POS"',
  enableDeliveryCharge: 'Habilitar "Cargo por delivery"',
  internalProductsHint:
    'Estos son productos que se crean como <strong>internos / ocultos</strong> para permitir:',
  registerPosTips: 'Registrar propinas cobradas en POS',
  applyDeliveryCharge: 'Aplicar cargo por delivery',
  internalDiscounts: 'Descuentos Internos',
  enableCourtesyDrinkDiscount: 'Habilitar descuento "Trago Cortesía"',
  servicePercentHint:
    'El porcentaje de servicio se usará para cálculos de precio final donde corresponda.',
  configSaved: 'Configuración guardada',
  couldNotSave: 'No se pudo guardar',
  identifierGenerated: 'Identificador generado',
  checkIdentifier: 'Revisa el identificador',
  identifierCannotBeEmpty: 'El identificador no puede estar vacío',
  identifierSavedOnComputer: 'Identificador guardado en este ordenador',
  noIdentifierToDelete: 'No hay identificador para eliminar',
  identifierDeleted: 'Identificador eliminado',
  checkRequiredFields: 'Revisa los campos requeridos',

  // Página de administración y menús (administracion, menu-ventas, menu-almacen)
  adminSubtitle: 'Configura ventas, almacén y parámetros del sistema.',
  salesCardSubtitle: 'Operaciones, cierres y reportes',
  warehouse: 'Almacén',
  warehouseCardSubtitle: 'Productos, stock y compras',
  menuMasters: 'Maestros',
  menuOperations: 'Operaciones',
  menuReports: 'Reportes',
  menuConfiguration: 'Configuración',
  menuWarehouseMovements: 'Movimientos',
  menuInventoryControl: 'Control de inventario',
  menuWarehouseTransformation: 'Transformación',
  zones: 'Ambientes',
  zonesConfig: 'Configuración de Ambientes',
  spaces: 'Espacios',
  spacesConfig: 'Configuración de Espacios',
  families: 'Familias',
  productFamilies: 'Familia de Productos',
  subfamiliesShort: 'Sub familias',
  productSubfamilies: 'Sub Familia de Productos',
  groups: 'Grupos',
  colors: 'Colores',
  printing: 'Impresión',
  partners: 'Socios',
  businessPartners: 'Socios de Negocio',
  combos: 'Menús',
  combosConfig: 'Configuración de menús',
  comboMaintenanceEyebrow: 'Mantenimiento de productos',
  comboMaintenanceHint: 'Define las opciones disponibles y cuántas puede elegir el cliente en cada sección del menú.',
  selectMainCombo: 'Seleccionar menú principal',
  mainCombo: 'Menú principal',
  noMainCombos: 'No hay menús principales disponibles.',
  createMainComboHint: 'Cree o edite un producto de tipo Menú y seleccione “Menú principal” como sección.',
  comboSections: 'Secciones del menú',
  availableProducts: 'Productos disponibles',
  noProductsForComboSection: 'No hay productos activos asignados a esta sección.',
  sectionConfiguration: 'Configuración de la sección',
  allowedQuantity: 'Cantidad permitida',
  selectedProducts: 'productos seleccionados',
  selectComboProductsHint: 'Seleccione los productos que el cliente podrá elegir.',
  deleteSectionConfig: 'Eliminar sección',
  saveSection: 'Guardar sección',
  remove: 'Quitar',
  menuSelection: 'Configurar menú',
  menuSelectionHint:
    'Elija los productos requeridos en cada sección. El menú se cobra como un solo producto.',
  menuQuantity: 'Cantidad de menús',
  menuNotConfigured: 'Menú sin configurar',
  menuNotConfiguredHint:
    'Configure este menú en Administración antes de agregarlo al pedido.',
  menuSections: 'Secciones del menú',
  chooseMenuOptions: 'Opciones disponibles',
  requiredQuantity: 'Requerido',
  selectedQuantity: 'Seleccionado',
  sectionComplete: 'Completa',
  sectionPending: 'Pendiente',
  selectedMenuOptions: 'Productos elegidos',
  noMenuOptions: 'No hay opciones disponibles en esta sección.',
  completeAllMenuSections:
    'Complete la cantidad requerida en todas las secciones del menú.',
  sectionRequiresQuantity:
    'La sección {{section}} requiere exactamente {{quantity}} unidades.',
  viewMenu: 'Ver menú',
  menuConfigured: 'Menú configurado',
  menuReadOnlyHint:
    'Este menú ya fue enviado. Puede consultar la selección, pero no modificarla.',
  employees: 'Empleados',
  users: 'Usuarios',
  station: 'Estación',
  discounts: 'Descuentos',
  cards: 'Tarjetas',
  promotions: 'Promociones',
  customers: 'Clientes',
  salesList: 'Listado de Ventas',
  accounting: 'Contable',
  salesByProductShort: 'Por producto',
  summary: 'Resumen',
  initialSetupShort: 'Config. inicial',
  thisStation: 'Esta estación',
  configureThisStation: 'Configurar esta estación',
  items: 'Artículos',
  recipes: 'Recetas',
  warehouseAreas: 'Áreas de almacén',
  warehouseSubareas: 'Subáreas de almacén',
  suppliers: 'Proveedores',
  stockIn: 'Ingresos',
  stockOut: 'Salidas',
  stockOutReasons: 'Motivos de salida',

  // Grupos de almacén
  warehouseGroups: 'Grupos de almacén',
  newWarehouseGroup: 'Nuevo grupo',
  editWarehouseGroup: 'Editar grupo de almacén',
  searchGroup: 'Buscar grupo',
  groupData: 'Datos del grupo',
  warehouseGroupsHint:
    'Agrupa insumos y artículos de almacén. Los grupos de productos de venta se mantienen desde Ventas.',
  groupTypeSupply: 'Insumo',
  groupTypeItem: 'Artículo',
  allTypes: 'Todos',
  noWarehouseGroupsFound: 'No se encontraron grupos de almacén.',
  deleteWarehouseGroupTitle: '¿Eliminar grupo de almacén?',
  groupDescriptionRequired: 'Ingrese la descripción del grupo.',
  couldNotLoadWarehouseGroups: 'No se pudieron cargar los grupos de almacén.',
  couldNotSaveGroup: 'No se pudo guardar el grupo.',
  couldNotDeleteGroup: 'No se pudo eliminar el grupo.',
  groupInUse: 'El grupo está siendo utilizado.',
  passwordChangeRedirectHint:
    'Te llevaremos a una página segura para cambiar tu contraseña. La contraseña nunca pasa por la aplicación.',
  transfers: 'Transferencias',
  inventories: 'Inventarios',
  stockByArea: 'Stock por área',
  warehouseKardex: 'Kardex de almacén',
  warehouseConsumptionByArea: 'Consumo por subárea',
  salesVersusCost: 'Venta vs. costo histórico',
  theoreticalVsActualConsumption: 'Consumo teórico vs. real',
  profitabilityByProductChannel: 'Rentabilidad por producto y canal',
  stockCoverage: 'Cobertura de stock',
  executiveAnalysis: 'Análisis ejecutivo',
  comparisonSales: 'Comparativo de ventas',
  comparisonSalesSubtitle: 'Rendimiento actual frente al período inmediatamente anterior',
  currentPeriod: 'Período actual',
  previousPeriod: 'Período anterior',
  documentsCount: 'Documentos',
  grossMargin: 'Margen bruto',
  profitability: 'Rentabilidad',
  marginEvolution: 'Venta, costo y margen',
  marginEvolutionSubtitle: 'Costo histórico fotografiado y evolución del margen bruto',
  analyzedSales: 'Venta analizada',
  historicalCost: 'Costo histórico',
  incompleteCostData: '{{count}} documentos no tienen fotografía de costo ({{amount}} en ventas) y no se incluyen en el margen.',
  cashFlow: 'Cobros',
  paymentDistribution: 'Pagos y divisas',
  paymentDistributionSubtitle: 'Cobro neto por método y montos originales en moneda extranjera',
  payments: 'pagos',
  currencyBreakdown: 'Desglose por moneda',
  netCollected: 'Cobro neto',
  originalAmount: 'Monto original',
  baseCurrencyEquivalent: 'Equivalente en moneda base',
  averageExchangeRate: 'Tipo de cambio promedio',
  legacyPaymentBreakdown: '{{count}} pagos históricos no contienen el monto original.',
  reportLoadError: 'No se pudo cargar el reporte.',
  portioning: 'Porcionamiento',
  production: 'Producción',
  timeTracking: 'Control horario',
};

export const ES_PE_OVERRIDES: Partial<Record<TenantTextKey, string>> = {
  orderAttendant: 'Mozo',
  changeOrderAttendant: 'Cambiar mozo',
  selectOrderAttendant: 'Seleccione un mozo',
  orderAttendantRequired: 'Debe seleccionar un mozo.',
  onlyAdminCanChangeOrderAttendant:
    'Solo el administrador puede cambiar el mozo.',
  couldNotChangeOrderAttendant: 'No se pudo cambiar el mozo.',
  unexpectedOrderAttendantChangeError:
    'Ocurrió un error al cambiar el mozo.',
};

export const ES_ES_OVERRIDES: Partial<Record<TenantTextKey, string>> = {
  orderAttendant: 'Camarero',
  changeOrderAttendant: 'Cambiar camarero',
  selectOrderAttendant: 'Seleccione un camarero',
  orderAttendantRequired: 'Debe seleccionar un camarero.',
  onlyAdminCanChangeOrderAttendant:
    'Solo el administrador puede cambiar el camarero.',
  couldNotChangeOrderAttendant: 'No se pudo cambiar el camarero.',
  unexpectedOrderAttendantChangeError:
    'Ocurrió un error al cambiar el camarero.',
};
