export const EN_TEXTS = {
  // Regional terminology
  orderAttendant: 'Waiter',
  changeOrderAttendant: 'Change waiter',
  selectOrderAttendant: 'Select a waiter',
  orderAttendantRequired: 'You must select a waiter.',
  onlyAdminCanChangeOrderAttendant:
    'Only an administrator can change the waiter.',
  couldNotChangeOrderAttendant: 'The waiter could not be changed.',
  unexpectedOrderAttendantChangeError:
    'An error occurred while changing the waiter.',

  // Common actions and states
  accept: 'Accept',
  cancel: 'Cancel',
  close: 'Close',
  closeDialog: 'Close dialog',
  delete: 'Delete',
  error: 'Error',
  validation: 'Validation',
  exit: 'Exit',
  search: 'Search',
  retry: 'Retry',
  save: 'Save',
  saving: 'Saving…',
  openStatus: 'OPEN',
  closedStatus: 'CLOSED',
  language: 'Language',
  useTenantLanguage: 'Use business language',
  cultureChangeError: 'The language preference could not be changed.',

  // Application and login
  restaurantManagement: 'Agile management for restaurants and hospitality',
  installApplication: 'Install application',
  invalidCredentials: 'Incorrect username or password. Please try again.',
  branch: 'Branch',
  user: 'User',
  usernamePlaceholder: 'Enter your username',
  password: 'Password',
  passwordPlaceholder: 'Enter your password',
  showPassword: 'Show password',
  hidePassword: 'Hide password',
  numericKeypad: 'Numeric keypad',
  signIn: 'Sign in',
  signingIn: 'Signing in…',
  forgotPassword: 'Forgot your password?',
  checkYourEmail: 'Check your email',
  resetEmailSentPrefix: 'If user',
  resetEmailSentSuffix:
    'has a registered email, you will receive a password reset link in the next few minutes.',
  backToLogin: 'Back to sign in',
  back: 'Back',
  recoverPassword: 'Recover password',
  recoverPasswordHint: 'We will send a link to your registered email.',
  usernameNamePlaceholder: 'Enter your username',
  sendInstructions: 'Send instructions',
  sending: 'Sending…',
  applicationVersion: 'Application version',
  serverOffline: 'No connection to the server',
  operationsUnavailable: 'operations are unavailable',
  enterPassword: 'Enter password',
  noBusinessRole:
    'The user does not have a business role assigned in Keycloak.',
  couldNotLoadStations: 'The station list could not be loaded.',
  stationNotConfigured: 'Station not configured',
  stationIdentifierMissing:
    'This device does not have a station identifier. Contact the administrator.',
  selectBranchAndUser: 'Select a branch and enter your username.',
  iosInstallHint:
    'To install the application on iOS, open the share menu and select "Add to Home Screen".',
  couldNotLoadTenants: 'The tenant list could not be loaded.',
  noTenantsAvailable:
    'There are no tenants available. Contact the administrator.',
  couldNotLoadTenantsRetry:
    'Tenants could not be loaded. Please try again.',

  // Header and navigation
  openMenu: 'Open menu',
  restaurant: 'Restaurant',
  shift: 'Shift',
  noShift: 'No shift',
  shiftSales: 'Shift sales',
  orders: 'Orders',
  averageTicket: 'Average ticket',
  home: 'Home',
  logout: 'Log out',
  dashboard: 'Dashboard',
  administration: 'Administration',
  register: 'Register',
  noOpenShiftForStation: 'There is no open shift for this station',
  componentWillClose: 'This screen will close.',
  change: 'Change',

  // Sales screen
  goToAdministration: 'Go to Administration',
  administrationShortcut: 'Administration (Ctrl+Alt+A)',
  date: 'Date',
  tableChannel: 'TABLE CHANNEL',
  takeawayChannel: 'TAKEAWAY CHANNEL',
  deliveryChannel: 'DELIVERY CHANNEL',
  admission: 'ADMISSION',
  refresh: 'REFRESH',
  orderNumber: 'Order No.',
  delivery: 'Delivery',
  phone: 'Phone',
  customer: 'Customer',
  order: 'Order',
  product: 'Product',
  observation: 'Note',
  hostess: 'Hostess',
  couponNumber: 'Coupon No.',
  withComplement: 'With complement',
  price: 'Price',
  quantity: 'Qty',
  increaseQuantity: 'Increase quantity',
  decreaseQuantity: 'Decrease quantity',
  moreOptions: 'More options',
  moveToAnotherTable: 'Move to another table',
  courtesyDrink: 'Complimentary drink',
  amount: 'Amount',
  discount: 'Discount',
  removeDiscount: 'Remove discount',
  total: 'Total',
  bagTax: 'Bag',
  preBill: 'Pre-bill',
  issuedDocuments: 'Issued documents',
  expensesReports: 'Expenses / Reports',
  combo: 'Menu',
  viewComplements: 'View complements',
  viewComplement: 'View complement',
  express: 'Express',
  sendOrder: 'Send order',
  lock: 'Lock',
  reset: 'Reset',
  prioritizeDispatch: 'Prioritize dispatch',
  cancelOrder: 'Cancel order',
  reprint: 'Reprint',
  mergeTablePrefix: 'will be merged into the selected table',
  occupiedTablesOnly: 'only occupied tables are shown',
  selectFreeTableForOrder: 'Select a free table to move the order',
  selectDestinationTable: 'Select the destination table for',
  verifyBackend: 'Check that the backend is running and try again.',
  newOrder: 'New order',
  processOrder: 'Process order',
  moveToTable: 'Move to table',
  changeSpace: 'Change space',
  mergeAccount: 'Merge account',
  splitAccount: 'Split account',
  activateSpace: 'Activate space',
  searchProducts: 'Search products',
  selectSpace: 'Select a space.',
  mergeSpace: 'Merge space',
  changeSpaceTitle: 'Change space',
  customerNamePlaceholder: 'Enter the customer name',
  courtesyCodeEntered: 'Complimentary code entered',
  enteredCode: 'The entered code is: {{code}}',
  deleteCode: 'Delete code',
  keepCode: 'Keep code',
  codeDeleted: 'Code deleted',
  enterCourtesyCode: 'Enter complimentary code',
  enterHostessCodes: 'Enter hostess codes',
  codeLabel: 'Code {{number}}',
  addMore: 'Add more',
  enterHostessCode: 'Enter hostess code {{number}}',
  orderNotFound: 'The order does not exist.',
  productTransfer: 'Product transfer',
  selectTable: 'You must select a table.',
  transferToTable: 'Transfer to table',
  selectOrder: 'You must select an order.',
  couldNotMoveOrder: 'The order could not be transferred.',
  errorMovingOrder: 'An error occurred while transferring the order.',
  couldNotTransferProduct: 'The product could not be transferred.',
  errorMovingProduct: 'An error occurred while transferring the product.',
  enterGuestCount: 'Enter number of guests',
  positiveNumberRequired: 'Enter a valid number greater than zero.',
  orderNotFoundInSpace: 'The order does not exist in this space.',
  unexpectedError: 'Something went wrong',
  addQuantityFirst: 'Add a quantity first.',
  confirmDeleteProduct: 'Are you sure you want to delete {{product}}?',
  enterAdministratorCode: 'Enter administrator code',
  invalidCode: 'Invalid code',
  incorrectCode: 'The entered code is incorrect.',
  enterPrice: 'Enter price',
  confirmVoidSpaceOrder:
    'Are you sure you want to void the order for {{space}}?',
  processOrderTitle: 'Process order',
  confirmRemoveDiscount: 'Are you sure you want to remove the discount?',
  yes: 'Yes',
  no: 'No',
  orderNotFoundInAccount: 'The order does not exist in the account.',
  printPreBill: 'Print pre-bill',
  noProductsEntered: 'No products have been entered.',
  allProductsMustBeSaved: 'Not all products in the list were saved.',
  orderMustBeSaved: 'The entire order must be saved.',
  internalErrorRefresh: 'Internal error. Please refresh.',

  // Shift dialogs
  closeShift: 'Close shift',
  shiftNumber: 'Shift No.',
  startDate: 'Start date',
  currentDate: 'Current date',
  exchangeRate: 'Exchange rate',
  status: 'Status',
  shiftClosed: 'SHIFT CLOSED',
  selectOpenShiftRegister:
    'Select a register with an open shift to close it.',
  partialClose: 'Partial close',
  partialCloseHint: 'Skips validation of unpaid orders.',
  pendingOrdersTitle: 'Orders pending payment ({{count}})',
  pendingOrdersExplanation:
    'These orders prevent the shift from closing. You can void them here or leave to collect them from Sales. Then try closing the shift again.',
  account: 'Account',
  spaceOrChannel: 'Space / channel',
  void: 'Void',
  revalidateClose: 'Revalidate close',
  openShift: 'Open shift',
  shiftOpened: 'Shift {{number}} open',
  registerAlreadyOperational:
    'The selected register is already operational. It does not need to be opened again.',
  selectRegister: 'Select a register.',
  enterExchangeRate: 'Enter the exchange rate.',
  enterPositiveValue: 'Enter a value greater than zero.',
  workDate: 'Work date',
  openAction: 'Open',
  noOpenShiftForRegister: 'There is no open shift for this register.',
  couldNotCloseShift: 'The shift could not be closed.',
  shiftCloseTitle: 'Shift closing',
  shiftClosedSuccessfully: 'The shift was closed successfully.',
  voidOrderTitle: 'Void order No. {{number}}',
  voidOrderWarning:
    'This operation will void the entire order and cannot be undone.',
  voidReason: 'Void reason',
  enterVoidReason: 'Enter the reason...',
  voidOrder: 'Void order',
  voidReasonRequired: 'You must enter the void reason.',
  couldNotVoidOrder: 'The order could not be voided.',
  orderVoided: 'Order voided',
  orderVoidedSuccessfully: 'The order was voided successfully.',
  unpaidSalesTitle: 'Sales without a recorded payment',
  unpaidSalesQuestion:
    'There are sales without a recorded payment. Are they credit sales?',
  document: 'Document',
  confirmCreditSales: 'Yes, they are credit sales',
  shiftOpenedTitle: 'Shift opened',
  registerAvailableForOperations:
    'The register is now available to record operations.',

  // Delivery
  newDelivery: 'New delivery',
  newDeliveryOrderTab: 'New order',
  deliveryOperationsTab: 'Dispatch and payment',
  deliveryOperationsTitle: 'Drivers and deliveries',
  deliveryOperationsHint:
    'Assign orders to in-house drivers and record payment when the driver returns.',
  pendingOwnDeliveries: '{{count}} pending deliveries',
  pendingDeliveryOrders: 'In-house delivery orders',
  pendingDeliveryOrdersHint:
    'The order is completed only after its payment is recorded.',
  loadingPendingDeliveries: 'Loading pending deliveries…',
  noPendingDeliveries: 'No pending deliveries',
  noPendingDeliveriesHint:
    'Paid orders disappear from this list automatically.',
  noAddress: 'No address recorded',
  ownDriver: 'In-house driver',
  noDriversAvailable: 'No employees are available for delivery.',
  assigningDriver: 'Assigning…',
  assignDriver: 'Assign driver',
  assignedDriver: 'Assigned driver',
  deliveryPaymentAlreadyRegistered: 'Payment already recorded',
  confirmDeliveryAndCharge: 'Confirm delivery and record payment',
  chooseDeliveryOrigin:
    'Choose how the order was received before identifying the customer.',
  businessPartnersCount: '{{count}} business partners',
  deliveryMode: 'Delivery method',
  phoneDelivery: 'Delivery by phone',
  phoneDeliveryHint:
    'Find or register the customer phone number and address.',
  businessPartnerOrder: 'Order from a business partner',
  businessPartnerExamples:
    'Glovo, Uber Eats or another platform with its own prices.',
  noBusinessPartners: 'No business partners are configured.',
  selectDeliveryMode: 'Select a method to continue',
  selectDeliveryModeHint:
    'This keeps the order origin and pricing rules correct.',
  externalOrderData: 'External order details',
  noPhoneRecordForExternalOrder:
    'A phone record is not created for this order',
  businessPartner: 'Business partner',
  selectOriginBusinessPartner:
    'Select the business partner that originated the order.',
  customerName: 'Customer name',
  customerNameRequired: 'The customer name is required.',
  unnamedCustomer: 'No name',
  businessPartnerPricesHint:
    'Configured partner prices will be applied. Products without a special price will keep their normal price.',
  deliverySearchLabel: 'Phone, customer, document or address',
  clearSearch: 'Clear search',
  newDestination: 'New destination',
  destinationsFound: 'Destinations found',
  destinations: 'Destinations',
  foundCount: '{{count}} found',
  loadingCustomers: 'Loading customers…',
  noDestinationFound: 'No destination found',
  registerWithoutLeavingSale:
    'You can register it without leaving the sale.',
  registerDestination: 'Register destination',
  selectDestination: 'Select a destination',
  createDestinationHint:
    'You can also create a new one to continue with the order.',
  deliveryData: 'Delivery details',
  newCustomerAddress: 'New customer address',
  newDestinationTitle: 'New destination',
  customerAddressReference:
    'Customer {{customer}} · Address {{address}}',
  customerReference: 'Customer {{customer}} · {{name}}',
  addAnotherAddress: 'Add another address for this customer',
  phoneValidation: 'Enter a phone number with 7 to 15 digits.',
  shortInstruction: 'Extension / short instruction',
  recipientName: 'Recipient name',
  nameRequired: 'The name is required.',
  deliveryAddress: 'Delivery address',
  addressRequired: 'The address is required.',
  reference: 'Reference',
  deliveryPrice: 'Delivery price',
  deliveryProductAdded: '{{product}} will be added to the order.',
  configureDeliveryProduct:
    'Configure the delivery charge product first.',
  priceCannotBeNegative: 'The price cannot be negative.',
  identityType: 'Identity type',
  identityNumber: 'Identity number',
  businessNameOrCustomer: 'Business name / customer name',
  fieldRequired: 'This field is required.',
  email: 'Email',
  validEmailRequired: 'Enter a valid email.',
  recentOrders: 'Recent orders',
  deliverySalesHistory: 'Customer delivery sales history',
  loadingHistory: 'Loading history…',
  noDeliverySales: 'There are no delivery sales for this customer yet.',
  productsCount: '{{count}} products',
  continueToOrder: 'Continue to order',
  checkingPrices: 'Checking prices…',
  // General sales tray
  generalSales: 'General sales list',
  allShiftsAndRegisters: 'All shifts and registers',
  includeExpressSales: 'Include express sales',
  searchBy: 'Search by',
  documentType: 'Document type',
  documentNumber: 'Document No.',
  currency: 'Currency',
  state: 'State',
  options: 'Options',
  saleFound: '{{count}} sale found',
  salesFound: '{{count}} sales found',
  fromTotal: 'of {{count}}',
  update: 'Update',
  newSale: 'New sale',
  issueCreditNote: 'Issue credit note',
  pendingUseCase: 'Use case pending implementation',
  saleActions: 'Sale actions',
  noSalesFound:
    'No sales were found for the selected criteria.',
  modifyDocument: 'Modify document',
  modifyPayments: 'Modify payments',
  getPdfAndXml: 'Get PDF and XML',
  reprintDocument: 'Reprint document',
  salesPagination: 'Sales pagination',
  selectDocument: 'Select a document.',
  selectSaleToVoid: 'Select a sale to void.',
  confirmVoidDocument: 'Are you sure you want to void document {{document}}?',
  actionCannotBeUndone: 'This action cannot be undone.',
  yesVoid: 'Yes, void',
  noCancel: 'No, cancel',
  voided: 'Voided',
  documentVoidedSuccessfully: 'The document was voided successfully.',
  couldNotVoidDocument: 'The document could not be voided.',

  // Payment and document issuing
  paymentAndIssueDocument: 'Payment and document issuing',
  documentData: 'Document details',
  series: 'Series',
  number: 'Number',
  customerData: 'Customer details',
  removeCustomerData: 'Remove customer details',
  customerDocumentType: 'Customer document type',
  requiredField: 'This field is required.',
  invalidExpectedFormat: 'Invalid format{{expected}}.',
  expectedFormat: ' — expected: {{mask}}',
  invalidNumberForAmount: 'Invalid number for the current amount.',
  miscellaneousCustomerRule:
    'The business name must be "Cliente Varios" when the document number is 00000001.',
  address: 'Address',
  invalidEmailFormat: 'The email format is incorrect.',
  addCustomerData: 'Add customer details',
  totalToPay: 'Total to pay',
  paidReference: 'of {{symbol}} {{total}} · paid {{symbol}} {{paid}}',
  cashPayments: 'Cash payments',
  exact: 'EXACT',
  automaticCharge: 'Auto-charge',
  exactCashHint:
    'Charge exactly {{symbol}} {{amount}} in cash and close automatically',
  currencyFallback: 'Currency',
  enter: 'Enter',
  entered: 'Entered',
  exchangeRateLabel: 'Exchange rate:',
  cardPayments: 'Card payments',
  card: 'Card',
  authorization: 'Authorization',
  paidAmount: 'Amount',
  tip: 'Tip',
  actions: 'Actions',
  add: 'Add',
  noCardPayments: 'No card payments recorded',
  charge: 'Charge',
  remaining: 'Remaining',
  changeDue: 'Change',
  paymentExcess: 'Excess',
  calculatedTotalMismatch:
    'The calculated amount does not match the register screen. Please try again.',
  totalTimeout: 'The total to pay could not be obtained. The request timed out.',
  system: 'System',
  registerInfoNotFound: 'Register information was not found.',
  selectedDocumentTypeNotFound:
    'The selected document type was not found.',
  getRegisterError: 'Error while loading the register.',
  cardAmountExceedsTotal:
    'The card amount exceeds the amount to pay.',
  enterCardPaymentAmount: 'Enter the amount paid by card.',
  mainCurrency: 'Main currency',
  selectCustomerIdentityType:
    'Select the customer identity document type.',
  enterCustomerIdentityNumber:
    'Enter the customer identity number.',
  enterCustomerBusinessName:
    'Enter the customer name or business name.',
  enterValidCustomerIdentity:
    'Enter a valid customer identity number.',
  enterCustomerAddress: 'Enter the customer address.',
  genericIdentityNameRule:
    'When the identity number is 00000001, the customer name must be "Cliente Varios".',
  genericCustomerIdentityRule:
    'When the customer is "Cliente Varios", the identity number must be 00000001.',
  amountRequiresCustomerIdentity:
    'For this amount, the customer identity document is required.',
  invalidCustomerEmail: 'The email address is invalid.',
  confirmChargeAccount: 'Are you sure you want to charge the account?',
  confirmCreditSale: 'Are you sure you want to record the credit sale?',
  message: 'Message',
  paymentBelowTotal:
    'The payment total is lower than the amount to pay.',
  preferredFormat: 'Which format do you prefer?',
  chooseOption: 'Choose an option',
  ticket: 'Receipt',
  customerNotFound: 'The customer was not found.',
  retrySearchTimeout: 'Search again. The request timed out.',
  amountCalculationError: 'An error occurred while calculating the amounts.',

  // Administration and maintenance
  description: 'Description',
  descriptionRequired: 'Description is required.',
  required: 'Required.',
  updateAction: 'Update',
  edit: 'Edit',
  active: 'Active',
  inactive: 'Inactive',
  family: 'Family',
  familyRequired: 'Family is required.',
  searchByDescription: 'Search by description',
  descriptionOrStatus: 'Description, status...',
  maintenanceFamilies: 'Family maintenance',
  newFamily: 'New family',
  maintenanceSubfamilies: 'Subfamily maintenance',
  newSubfamily: 'New subfamily',
  productGroups: 'Product groups',
  newGroup: 'New group',
  maintenancePrintAreas: 'Print area maintenance',
  newPrintArea: 'New area',
  descriptionOrPrinter: 'Description or printer...',
  printerName: 'Printer name',
  printerExample: 'E.g. EPSON_TM20, HP_LaserJet...',
  maintenanceColors: 'Color maintenance',
  newColor: 'New color',
  descriptionOrRgb: 'Description or RGB',
  color: 'Color',
  chooseColor: 'Choose color',
  maintenanceStations: 'Station maintenance',
  newStation: 'New station',
  searchStation: 'Search by name or unique identifier',
  uniqueIdentifier: 'Unique identifier',
  type: 'Type',
  stationType: 'Station type',
  assignedRegister: 'Assigned register',
  maintenanceEnvironments: 'Zone maintenance',
  newEnvironment: 'New zone',
  searchEnvironment: 'Search by description, status or position',
  position: 'Position',
  selectState: 'Select a status.',
  selectPosition: 'Select a position (1 to 10)',
  choosePosition: 'Choose position (1 × 10)',
  maintenanceObservations: 'Note maintenance',
  newObservation: 'New note',
  descriptionTypePosition: 'Description, type, position...',
  observationExample: 'E.g. VERY HOT, SAUCE ON THE SIDE, ...',
  selectGridPosition: 'Select the position ({{rows}} x {{cols}}) — Type: {{type}}',
  selected: 'Selected',
  occupied: 'Occupied',
  free: 'Free',
  maintenanceEmployees: 'Employee maintenance',
  newEmployee: 'New employee',
  searchEmployee: 'Search by name, identity document, etc.',
  name: 'Name',
  identityDocument: 'Identity document',
  identityRequired: 'The identity document is required.',
  nameRequiredField: 'The name is required.',
  addressRequiredField: 'The address is required.',
  telephone: 'Phone',
  validPhoneRequired: 'Enter a valid phone number.',

  // Register maintenance (caja)
  maintenanceRegisters: 'Register maintenance',
  newRegister: 'New register',
  searchRegister: 'Description, default...',
  defaultRegister: 'Default register',
  salesChannel: 'Sales channel',
  enabledSalesChannels: 'Enabled sales channels',
  defaultSalesChannel: 'Default sales channel',
  selectAtLeastOneChannel: 'Select at least one channel above.',
  emitsPreBill: 'Issues pre-bill',
  emitsKitchenTicket: 'Issues kitchen ticket',
  emitsDiscount: 'Issues discount',
  allowsSplitOrder: 'Allows splitting order',
  allowsPartialClose: 'Allows partial close',
  onlineElectronicSubmission: 'Online electronic submission',
  automaticDeliveryPreBill: 'Automatic delivery pre-bill',
  allowTaxiPayments: 'Allow taxi payments',

  // Discount maintenance (descuento)
  maintenanceDiscounts: 'Discount maintenance',
  newDiscount: 'New discount',
  searchDiscount: 'Description, type...',
  percentage: 'Percentage',
  clickToActivate: 'Click to activate',
  clickToDeactivate: 'Click to deactivate',
  noDiscountsRegistered: 'No discounts registered.',
  editDiscount: 'Edit discount',
  discountType: 'Discount type',
  selectType: 'Select a type.',
  enterPercentageGreaterThanZero: 'Enter a percentage greater than 0.',
  valeTypeNoPercentage: 'The Voucher type does not require a percentage.',

  // Customer maintenance (cliente)
  maintenanceCustomers: 'Customer maintenance',
  newCustomer: 'New customer',
  searchCustomer: 'Search by name, tax ID, etc.',
  businessName: 'Business name',
  businessNameRequired: 'The business name is required.',

  // Product maintenance (producto)
  maintenanceProducts: 'Product maintenance',
  newProduct: 'New product',
  searchProduct: 'Name, description, price, position...',
  shortName: 'Short name',
  visible: 'Visible',
  productTypeMenuCard: 'À la carte',
  productTypeMenu: 'Menu',
  productTypeWithComplements: 'With add-ons',
  productTypeComplement: 'Add-on',
  subfamily: 'Subfamily',
  group: 'Group',
  menuSection: 'Menu section',
  requiredForMenu: 'Required for Menu.',
  complementsQuantity: 'Number of add-ons',
  requiredForType2: 'Required for Type = 2.',
  complementFactor: 'Add-on factor',
  complementFactorHint: '> 0 (2 decimals).',
  complementPosition: 'Add-on position',
  selectPosition6x5: 'Select position 6×5',
  choosePosition6x5: 'Choose position (6×5)',
  selectPosition8x9: 'Select position 8×9',
  choosePosition8x9: 'Choose position (8×9)',
  minimumPrice: 'Minimum price',
  requiredIfNoPrice: 'Required if "No price".',
  idAndClassification: 'Identification and classification',
  configAndPrintAreas: 'Configuration and print areas',
  tax: 'Tax',
  noPrice: 'No price',
  exclusiveHostess: 'Hostess exclusive',
  allowsCourtesyDrink: 'Allows courtesy drink',
  printAreas: 'Print areas',
  printAreasHint: 'Select one or more areas where this product will print its kitchen ticket.',
  invalidPrice: 'Invalid price.',

  // Business partner maintenance (socio-negocio)
  maintenanceBusinessPartners: 'Business partner maintenance',
  newBusinessPartner: 'New partner',
  searchBusinessPartner: 'Search partner',
  commission: 'Commission',
  configuredPrices: 'Configured prices',
  editPartnerAndPrices: 'Edit partner and prices',
  deleteBusinessPartner: 'Delete partner',
  loadingBusinessPartners: 'Loading partners…',
  businessPartnerName: 'Business partner name',
  businessPartnerNameRequired: 'The partner name is required.',
  mustBeBetween0And100: 'Must be between 0 and 100.',
  partnerActiveForDelivery: 'Partner active for delivery',
  specialProductPrices: 'Special prices per product',
  normalPrice: 'Normal price',
  partnerPrice: 'Partner price',
  useNormalPrice: 'Use normal price',
  noProductsMatchSearch: 'No products match the search.',
  saveBusinessPartner: 'Save partner',
  backToList: 'Back to list',

  // Space maintenance (espacios)
  maintenanceSpaces: 'Space maintenance',
  newSpace: 'New space',
  searchSpace: 'Search by description, number, position or environment',
  environment: 'Zone',
  selectEnvironment: 'Select a zone.',
  numberRequiredGreaterThanZero: 'The number is required and must be greater than 0.',
  selectPositionSimple: 'Select a position',
  choosePositionSimple: 'Choose position',
  selectIfActive: 'Select whether it is active.',
  selectIfVisible: 'Select whether it is visible.',

  // User maintenance (usuarios)
  maintenanceUsers: 'User maintenance',
  newUser: 'New user',
  searchUser: 'Search by username, user level, etc.',
  username: 'Username',
  level: 'Level',
  usernameRequired: 'The username is required.',
  passwordRequired: 'The password is required.',
  employee: 'Employee',
  selectValidEmployee: 'Select a valid employee.',
  selectRole: 'Select a role.',
  changePassword: 'Change password',
  cancelChange: 'Cancel change',
  currentPassword: 'Current password',
  newPassword: 'New password',
  confirmPassword: 'Confirm password',
  passwordsDoNotMatch: 'The passwords do not match',
  savePassword: 'Save password',

  // Small dialogs (mcant, mtext, delete-product, mozo)
  switchToNumeric: 'Switch to numeric',
  switchToLetters: 'Switch to letters',
  clear: 'Clear',
  confirmVoidTitle: 'Confirm void',
  administrator: 'Administrator',
  authenticate: 'Authenticate',
  tableData: 'Table data',
  tableNumber: 'Table no.',
  guests: 'Guests',
  onlyNumbers: 'Only numbers',
  observations: 'Notes',
  writeManualObservation: 'Write manual note',
  food: 'Food',
  drinks: 'Drinks',
  selectPositionTitle: 'Select position',

  // Admission / taxi driver dialogs (entradas, pagar-taxista)
  admissionQuery: 'Admission inquiry',
  taxiDriverData: 'Taxi driver details',
  idDocument: 'ID',
  givenNames: 'Names',
  licensePlate: 'Plate',
  admissionsCourtesyDrinks: 'Admissions · complimentary drinks',
  searchByCode: 'Search by code',
  selectAdmissionHint: 'Select an admission from the list to calculate the Total to Pay.',
  docTypeShort: 'Doc type',
  promoCode: 'Promo code',
  registrationDate: 'Reg. date',
  noResultsForCode: 'No results for that code.',
  noAdmissionsRegistered: 'No admissions registered.',
  payTaxiDriver: 'Pay taxi driver',
  admissionSales: 'Admission sales',
  memberAdmission: 'Member admission',
  guestAdmission: 'Guest admission',
  processFreeAdmission: 'Process free admission',
  consumptionAdmission: 'Admission by consumption',
  processConsumptionAdmission: 'Process consumption admission',
  nationalAdmission: 'National admission',
  internationalAdmission: 'International admission',
  admissionsLower: 'admissions',
  newPrice: 'New price',
  freeDrinks: 'Free drinks',
  courtesyDrinksLower: 'complimentary drinks',
  subtract: 'Subtract',
  cameWithTaxiDriver: 'Came with taxi driver',
  addNationalAdmission: 'Add national admission',
  addInternationalAdmission: 'Add international admission',
  salesReceipt: 'Receipt',
  invoice: 'Invoice',

  // Accounting report dialog (reportecontable)
  reportType: 'Report type',
  accountingReport: 'Accounting report',
  sales: 'Sales',
  purchases: 'Purchases',
  initialDate: 'Start date',
  finalDate: 'End date',
  endDateBeforeStart: 'The end date cannot be earlier than the start date.',
  allMasculine: 'All',
  allFeminine: 'All',
  exporting: 'Exporting…',
  exportToExcel: 'Export to Excel',
  colorRed: 'RED',
  colorBlue: 'BLUE',
  colorWhite: 'WHITE',
  colorBlack: 'BLACK',
  colorYellow: 'YELLOW',

  // Product search / complements / order summary dialogs
  searchByProduct: 'Search by product',
  typeToFilter: 'Type to filter…',
  complements: 'Add-ons',
  selectComplement: 'Select add-on',
  addOnsQty: 'Add-ons qty',
  factorShort: 'Ft',
  increase: 'Increase',
  limit: 'Limit',
  orderSummary: 'ORDER SUMMARY',
  moreProducts: 'More products',

  // Discount / split-account dialogs
  discountBySale: 'Sale discount',
  byProduct: 'By product',
  voucher: 'Voucher',
  searchDiscountLabel: 'Search discount',
  descriptionEllipsis: 'Description...',
  noDiscountsForType: 'No discounts for this type.',
  newAccount: 'New account',
  showOrder: 'Show order',
  space: 'Space',
  accounts: 'Accounts',
  accountNumber: 'Account no.',
  products: 'Products',
  quantityFull: 'Quantity',
  tapProductToMove: 'Tap a product to move it →',
  tapProductToReturn: 'Tap a product to return it ←',
  confirm: 'Confirm',

  // Discount dialog logic (dialog-descuento .ts)
  amountLabel: 'Amount',
  numberLabel: 'Number',
  reservationNumber: 'Reservation no.',
  enterDiscountForSale: 'Enter a discount for the sale',
  maxVoucherDiscount: 'The maximum voucher discount must be {{max}}.',
  enterCouponVoucherReservation: 'Enter the coupon, voucher or reservation number',
  enterVoucherValue: 'Enter the voucher value',
  confirmExecuteDiscount: 'Are you sure you want to apply the discount?',

  // Quick sale / issued documents dialogs
  quickSaleRecord: 'Quick sale record',
  documentDate: 'Document date',
  currencySoles: 'SOLES',
  currencyDollars: 'DOLLARS',
  shiftDate: 'Shift date',
  sell: 'Sell',
  buy: 'Buy',
  onlyNumericValues: 'Enter only numeric values.',
  grandTotal: 'Grand total',
  salesDocuments: 'Sales documents',
  onCredit: 'On credit',
  mixed: 'Mixed',
  doiNumber: 'ID No.',
  paymentMethodShort: 'Pay. method',
  pdfAndXml: 'PDF and XML',
  voidReasonPlaceholder: 'Void reason (required to void)',
  virtualKeyboard: 'Virtual keyboard',
  correctIssuedSale: 'Correct issued sale',
  correctIssuedSaleHint: 'Choose what needs to be corrected',
  correctionKeepsAuditTrail:
    'The original document is never overwritten. The system will show the applicable fiscal treatment before making changes.',
  loadingDocumentCorrection: 'Loading document data...',
  correctionPayments: 'Payment methods',
  correctionPaymentsHint: 'Change cash, card or split payment without changing fiscal sale terms.',
  correctionCustomer: 'Customer details',
  correctionCustomerHint: 'Correct the identity, legal name, address or email printed on the document.',
  correctionDocumentType: 'Document type',
  correctionDocumentTypeHint: 'Replace the receipt or invoice with the required document type.',
  cash: 'Cash',
  courtesy: 'Courtesy',
  cheque: 'Cheque',
  deposit: 'Deposit',
  addPaymentMethod: 'Add payment method',
  paymentNetTotal: 'Net payment total',
  targetDocumentType: 'New document type',
  documentGivenToCustomer: 'The original document was given to the customer',
  documentGivenToCustomerHint:
    'For SUNAT this determines whether a cancellation notice can be used or a credit note is required.',
  correctionReasonPlaceholder: 'Explain why this correction is required',
  correctionReasonRequired: 'Enter a reason of at least 3 characters.',
  confirmPaymentChange: 'Confirm payment change',
  confirmPaymentChangeHint: 'The new payment methods will be saved. Do you want to continue?',
  applyPaymentChange: 'Apply change',
  confirmCustomerCorrection: 'Confirm customer correction',
  confirmCustomerCorrectionHint: 'A new receipt will be issued with the corrected customer details. Do you want to continue?',
  confirmDocumentChange: 'Confirm document change',
  confirmDocumentChangeHint: 'A new receipt of the selected type will be issued. Do you want to continue?',
  applyCorrection: 'Apply correction',
  reviewCorrection: 'Review correction',
  correctionConfirm: 'Confirm and apply',
  correctionApplied: 'Correction recorded',
  correctionCompleteRequiredFields:
    'Complete the required fields and make sure the net payment matches the sale total.',
  correctionCustomerRequiredFields:
    'Complete the required customer and document details.',
  correctionIdentityTypeRequired: 'Select the customer identity type.',
  correctionIdentityTypeNotValidForInvoice:
    'Select an identity type allowed for invoices.',
  correctionIdentityNumberRequired:
    'Enter the customer identity number.',
  correctionIdentityNumberInvalid:
    'The number does not have a valid {{type}} format.',

  // Issued-documents dialog logic (dialog-documentos-emitidos .ts)
  ok: 'OK',
  enterVoidReasonMsg: 'Enter the void reason',
  noPermissionEnterAdminKey:
    'You do not have permission. Enter the administrator password.',
  confirmVoidThisDocument: 'Are you sure you want to void the document?',
  voidOrderTitleSimple: 'Void order',
  alsoVoidOrder: 'Also void the order?',
  administratorCode: 'Administrator code',
  operationCancelled: 'Operation cancelled',
  attention: 'Attention',

  // Quick sale dialog logic (dialog-emitir-venta .ts)
  mustOpenShiftToIssue:
    'You must open a shift for {{register}} to issue a sales document.',
  cannotAddQtyCombo:
    'A quantity cannot be added from this option for a Combo product.',
  cannotAddQtyComplements:
    'A quantity cannot be added from this option for a product with add-ons.',
  productInSolesNeedBuyRate:
    'The product {{product}} is priced in SOLES. To sell in DOLLARS you must enter the BUY exchange rate.',
  productInDollarsNeedSellRate:
    'The product {{product}} is priced in DOLLARS. To sell in SOLES you must enter the SELL exchange rate.',
  productNoStockContinue:
    'The product has no stock. Do you want to continue anyway?',
  noSaleProductEntered: 'You have not entered any sale product.',

  // Dashboard reports
  reportsDashboard: 'Reports dashboard',
  dashboardSubtitle:
    'Analyze sales, dish popularity and performance by date range.',
  dashboardFooter: '© 2024 LaComanda · Restaurant dashboard.',
  noDataForRange: 'No data for the selected range.',
  period: 'Period',
  daily: 'Daily',
  weekly: 'Weekly',
  monthly: 'Monthly',
  dailyWeeklyMonthly: 'Daily · Weekly · Monthly',
  dailySales: 'Daily sales',
  loadingSales: 'Loading sales...',
  totalSale: 'Total sales',
  loadingChannels: 'Loading channels...',
  salesByChannel: 'Sales by channel',
  spaceTakeawayDelivery: 'Dine-in · Takeaway · Delivery',
  takeaway: 'Takeaway',
  loadingPopularity: 'Loading popularity...',
  dishPopularity: 'Dish popularity',
  topBestSellingDishes: 'Top best-selling dishes',
  top: 'Top',
  loadingPeakHours: 'Loading peak hours...',
  peakHours: 'Peak hours',
  daySegments: 'Segments of the day',
  timeSlot: 'Time slot',
  afternoon: 'Afternoon',
  night: 'Night',
  lateNight: 'Late night',
  peakHour: 'Peak hour',
  transactions: 'Transactions',
  totalTransactions: 'Total transactions',
  loadingVoids: 'Loading voids...',
  voids: 'Voids',
  byProductAndReason: 'By product and reason',
  reason: 'Reason',
  authorizedBy: 'Authorized by',

  // Order list / view order / register documents dialogs
  orderList: 'ORDER LIST',
  select: 'Select',
  orderTime: 'Order time',
  documentsByRegister: 'Documents by register',
  loading: 'Loading...',
  enableAll: 'Enable all',
  disableAll: 'Disable all',
  currentNumber: 'Current #',
  copies: 'Copies',
  itemsPerDoc: 'Items / doc',
  askWhenPrinting: 'Ask when printing',
  mask: 'Mask',

  // Expenses & reports dialog (dialog-reportes)
  openPrint: 'Open / Print',
  print: 'Print',
  closeView: 'Close view',
  collectionsSummary: 'Collections summary',
  collected: 'Collected',
  pendingCollection: 'Pending collection',
  salesReports: 'Sales reports',
  adminsOnly: 'Administrators only',
  viewPdf: 'View PDF',
  generating: 'Generating...',
  salesByProduct: 'Sales by product',
  salesSummary: 'Sales summary',
  documentsSummary: 'Documents summary',
  onlyElectronicDocs: 'Electronic docs only',
  onlyExpress: 'Express only',
  expenses: 'Expenses',
  shiftExpenses: 'Shift expenses',
  expenseEntry: 'Expense entry',
  detailedReport: 'Detailed report',
  summaryReport: 'Summary report',
  tracking: 'Tracking',
  orderTracking: 'Order tracking',
  hostessCommission: 'Hostess commission',

  // Configure this computer (configurar-ordenador)
  configureThisComputer: 'Configure this computer',
  identifierPlaceholder: 'E.g. 9b5d-... or your own alias',
  identifierHint: 'Only letters, numbers, “-”, “_” or “.” — 6 to 64 characters',
  min6Chars: 'Minimum 6 characters',
  max64Chars: 'Maximum 64 characters',
  invalidFormat: 'Invalid format',
  generate: 'Generate',
  deleteIdentifier: 'Delete identifier',
  current: 'Current',
  notConfigured: '(not configured)',
  hostReference: 'Host (reference)',
  identifierStorageNote:
    'This identifier is stored on this computer (cookie) and will be used at sign-in to associate this station in the system.',

  // Initial setup (configuracion-inicial)
  initialSetup: 'Initial setup',
  businessData: 'Business details',
  countryIso2: 'Country (ISO2)',
  defaultCurrency: 'Default currency',
  symbol: 'Symbol',
  format: 'Format',
  invalidFormatForCountryType: 'Invalid format for the selected country / type.',
  tradeName: 'Trade name',
  servicePercent: '% Service',
  min0Percent: 'Minimum 0%',
  receiptFooter: 'Footer (receipt)',
  operation: 'Operation',
  transfer: 'Transfer',
  allowPreBills: 'Allow pre-bills',
  allowSpaceChange: 'Allow space change',
  dailyControl: 'Daily control',
  preBillsNumber: 'Number of pre-bills',
  closingReports: 'Closing reports',
  settlement: 'Settlement',
  itemConsumption: 'Item consumption',
  dailyExpenses: 'Daily expenses',
  includeExpressInClosing: 'Include "Express" in closing',
  includeExpressHint:
    'If <strong>Include Express in closing</strong> is active, internal receipts (with no fiscal effect) will be included in the reports marked above.',
  features: 'Features',
  enableHostessField: 'Enable "Hostesses" field in Products',
  hostessFieldHint:
    'If active, the <strong>ExclusivoParaAnfitriona</strong> field will be shown and enabled in product maintenance.',
  internalProducts: 'Internal products',
  enablePosTips: 'Enable "tips charged at POS"',
  enableDeliveryCharge: 'Enable "Delivery charge"',
  internalProductsHint:
    'These are products created as <strong>internal / hidden</strong> to allow:',
  registerPosTips: 'Record tips charged at POS',
  applyDeliveryCharge: 'Apply delivery charge',
  internalDiscounts: 'Internal discounts',
  enableCourtesyDrinkDiscount: 'Enable "Courtesy drink" discount',
  servicePercentHint:
    'The service percentage will be used for final-price calculations where applicable.',
  configSaved: 'Configuration saved',
  couldNotSave: 'Could not save',
  identifierGenerated: 'Identifier generated',
  checkIdentifier: 'Check the identifier',
  identifierCannotBeEmpty: 'The identifier cannot be empty',
  identifierSavedOnComputer: 'Identifier saved on this computer',
  noIdentifierToDelete: 'There is no identifier to delete',
  identifierDeleted: 'Identifier deleted',
  checkRequiredFields: 'Check the required fields',

  // Administration page & menus (administracion, menu-ventas, menu-almacen)
  adminSubtitle: 'Configure sales, warehouse and system parameters.',
  salesCardSubtitle: 'Operations, closings and reports',
  warehouse: 'Warehouse',
  warehouseCardSubtitle: 'Products, stock and purchases',
  menuMasters: 'Masters',
  menuOperations: 'Operations',
  menuReports: 'Reports',
  menuConfiguration: 'Configuration',
  zones: 'Zones',
  zonesConfig: 'Zone configuration',
  spaces: 'Spaces',
  spacesConfig: 'Space configuration',
  families: 'Families',
  productFamilies: 'Product families',
  subfamiliesShort: 'Subfamilies',
  productSubfamilies: 'Product subfamilies',
  groups: 'Groups',
  colors: 'Colors',
  printing: 'Printing',
  partners: 'Partners',
  businessPartners: 'Business partners',
  combos: 'Menus',
  combosConfig: 'Menu configuration',
  comboMaintenanceEyebrow: 'Product maintenance',
  comboMaintenanceHint: 'Define the available options and how many the customer can choose in each menu section.',
  selectMainCombo: 'Select main menu',
  mainCombo: 'Main menu',
  noMainCombos: 'No main menus are available.',
  createMainComboHint: 'Create or edit a Menu product and select “Main menu” as its section.',
  comboSections: 'Menu sections',
  availableProducts: 'Available products',
  noProductsForComboSection: 'There are no active products assigned to this section.',
  sectionConfiguration: 'Section configuration',
  allowedQuantity: 'Allowed quantity',
  selectedProducts: 'products selected',
  selectComboProductsHint: 'Select the products the customer may choose.',
  deleteSectionConfig: 'Delete section',
  saveSection: 'Save section',
  remove: 'Remove',
  menuSelection: 'Configure menu',
  menuSelectionHint:
    'Choose the required items in every section. The menu is charged as one product.',
  menuQuantity: 'Number of menus',
  menuNotConfigured: 'Menu not configured',
  menuNotConfiguredHint:
    'Configure this menu in Administration before adding it to an order.',
  menuSections: 'Menu sections',
  chooseMenuOptions: 'Available options',
  requiredQuantity: 'Required',
  selectedQuantity: 'Selected',
  sectionComplete: 'Complete',
  sectionPending: 'Pending',
  selectedMenuOptions: 'Selected menu items',
  noMenuOptions: 'There are no available options in this section.',
  completeAllMenuSections:
    'Complete the required quantity in every menu section.',
  sectionRequiresQuantity:
    'The section {{section}} requires exactly {{quantity}} units.',
  viewMenu: 'View menu',
  menuConfigured: 'Menu configured',
  menuReadOnlyHint:
    'This menu was already sent. Its selection can be viewed but not changed.',
  employees: 'Employees',
  users: 'Users',
  station: 'Station',
  discounts: 'Discounts',
  cards: 'Cards',
  promotions: 'Promotions',
  customers: 'Customers',
  salesList: 'Sales list',
  accounting: 'Accounting',
  salesByProductShort: 'By product',
  summary: 'Summary',
  initialSetupShort: 'Initial setup',
  thisStation: 'This station',
  configureThisStation: 'Configure this station',
  items: 'Items',
  recipes: 'Recipes',
  stockIn: 'Stock in',
  stockOut: 'Stock out',
  transfers: 'Transfers',
  inventories: 'Inventories',
  portioning: 'Portioning',
  production: 'Production',
} as const;

export type TenantTextKey = keyof typeof EN_TEXTS;
export type TenantTextParams = Record<
  string,
  string | number | null | undefined
>;
