apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: frontend-production   # ⚠️

resources:
  - ../../base
  - ingress.yaml
  - managed-cert.yaml
  - frontendconfig.yaml

images:
  - name: oscar020/frontend
    newName: oscar020/frontend
    newTag: 20251025-prod  # ⚠️ pipeline lo cambia
