apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: frontend-appweb-staging

resources:
- ../../base
- namespace.yaml
- ingress.yaml
- managed-cert.yaml
- frontendconfig.yaml

images:
- name: oscar020/frontend
  newName: oscar020/frontend
  newTag: 202510252018-feddac8-staging
