apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: frontend-appweb-staging

resources:
- ../../base
- namespace.yaml

images:
- name: oscar020/frontend
  newName: oscar020/frontend
  newTag: 202609050803-27508b8-staging
