name: CI/CD Pipeline - Frontend

on:
  push:
    branches:
      - master  # Ejecuta el workflow en push a la rama 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Ajusta la versión según la que uses en tu proyecto

    - name: Install dependencies
      run: npm install

   # - name: Run tests
   #   run: npm test -- --watch=false --no-progress --browsers=ChromeHeadless  # Ajusta este comando según tu configuración

    - name: Build Angular app
      run: npm run build -- --configuration production # Construir la aplicación para producción
      
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: frontend-artifact
        path: ./dist/jbs-rest   # Cambia 'jbs-rest' si tu build genera archivos en otro lugar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download Build Artifact
      uses: actions/download-artifact@v3
      with:
        name: frontend-artifact

    - name: Install lftp
      run: sudo apt-get install lftp

    - name: List Built Files
      run: ls -la . # Asegúrate de que esta ruta es correcta

    - name: Deploy to FTP server - Naruto Folder
      run: |
        lftp -e "set ftp:ssl-allow no; 
        open -u ${{ secrets.FTP_USER }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_HOST }}; 
        mirror -R . /naruto.jobbusiness.pe; 
        mirror -R . /main.jobbusiness.pe; bye"
